USE TIGER_FERCAM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE DP_RAPOR_BILANCO @DB NVARCHAR(50), @FIRM NVARCHAR(3), @DONEM NVARCHAR(2) ,
                                      @_BASTAR_VALUE DATETIME,
                                      @_BITTAR_VALUE DATETIME
 
AS
BEGIN
     DECLARE @QUERY NVARCHAR(MAX)
     DECLARE @QUERY1 NVARCHAR(MAX)
     DECLARE @QUERY2 NVARCHAR(MAX)
     DECLARE @QUERY3 NVARCHAR(MAX)
     DECLARE @QUERY4 NVARCHAR(MAX)
     DECLARE @QUERY5 NVARCHAR(MAX)
     DECLARE @QUERY6 NVARCHAR(MAX)
     DECLARE @QUERY7 NVARCHAR(MAX)
     DECLARE @QUERY8 NVARCHAR(MAX)
     DECLARE @QUERY9 NVARCHAR(MAX)
     DECLARE @QUERY10 NVARCHAR(MAX)
     DECLARE @QUERY11 NVARCHAR(MAX)
     DECLARE @QUERY12 NVARCHAR(MAX)
     DECLARE @QUERY13 NVARCHAR(MAX)
     DECLARE @QUERY14 NVARCHAR(MAX)
     DECLARE @QUERY15 NVARCHAR(MAX)
     DECLARE @QUERY16 NVARCHAR(MAX)
     DECLARE @QUERY17 NVARCHAR(MAX)
     DECLARE @QUERY18 NVARCHAR(MAX)
     DECLARE @QUERY19 NVARCHAR(MAX)
     DECLARE @QUERY20 NVARCHAR(MAX)

     DECLARE @PARAMETRELER NVARCHAR(MAX)

     SET @PARAMETRELER = N'@_BASTAR DATETIME,@_BITTAR DATETIME';

     SET @QUERY1 = ''
     SET @QUERY2 = ''
     SET @QUERY3 = ''
     SET @QUERY4 = ''
     SET @QUERY5 = ''
     SET @QUERY6 = ''
     SET @QUERY7 = ''
     SET @QUERY8 = ''
     SET @QUERY9 = ''
     SET @QUERY10 = ''
     SET @QUERY11 = ''
     SET @QUERY12 = ''
     SET @QUERY13 = ''
     SET @QUERY14 = ''
     SET @QUERY15 = ''
     SET @QUERY16 = ''
     SET @QUERY17 = ''
     SET @QUERY18 = ''
     SET @QUERY19 = ''
     SET @QUERY20 = ''

     SET @QUERY1 = SUBSTRING('select
CASE WHEN SUBSTRING(EMFLINE.KEBIRCODE,1,1)<3 THEN  ''Aktif Varlıklar''  ELSE ''Pasif Varlıklar'' END as Tip1, 
CASE WHEN SUBSTRING(EMFLINE.KEBIRCODE,1,1)=1 THEN  ''I.DÖNEN VARLIKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=2) THEN  ''II.DURAN VARLIKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=3) THEN  ''I.KISA VADELİ YABANCI KAYNAKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=4) THEN  ''II.UZUN VADELİ YABANCI KAYNAKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=5) THEN  ''III.ÖZ KAYNAKLAR''  ELSE ''DİĞER'' END ) END ) END ) END ) END as Tip2, 
CASE  SUBSTRING(EMFLINE.KEBIRCODE,1,2) WHEN 10 THEN  ''A.HAZIR DEĞERLER''  
WHEN 11 THEN  ''B.MENKUL KIYMETLER''  
WHEN 12 THEN  ''C.TİCARİ ALACAKLAR''  
WHEN 13 THEN  ''D.DİĞER ALACAKLAR''  
WHEN 15 THEN  ''E.STOKLAR'' 
WHEN 17 THEN  ''F.YILLARA YAYGIN İNŞAAT VE ONARIM MALİYETLERİ'' 
WHEN 18 THEN  ''G.GELECEK AYLARA AİT GİDERLER VE GELİR TAHAKUKLARI'' 
WHEN 19 THEN  ''H.DİĞER DÖNEN VARLIKLAR'' 
WHEN 22 THEN  ''A.TİCARİ ALACAKLAR''
WHEN 23 THEN  ''B.DİĞER ALACAKLAR''
WHEN 24 THEN  ''C.MALİ DURAN VARLIKLAR''
WHEN 25 THEN  ''D.MADDİ DURAN VARLIKLAR''
WHEN 26 THEN  ''E.MADDİ OLMAYAN DURAN VARLIKLAR''
WHEN 27 THEN  ''F.ÖZEL TÜKENMEYE TABİ VARLIKLAR ''
WHEN 28 THEN  ''G.GELECEK YILLARA AİD GİDERLER VE GELİR TAHAKUKLARI''  
WHEN 29 THEN  ''H.DİĞER DURAN VARLIKLAR'' 
WHEN 30 THEN  ''A.MALİ BORÇLAR''
WHEN 32 THEN  ''B.TİCARİ BORÇLAR'' 
WHEN 33 THEN  ''C.DİĞER BORÇLAR'' 
WHEN 34 THEN  ''D.ALINAN AVANSLAR'' 
WHEN 35 THEN  ''E.YILLARA YAYGIN İNŞAAT VE ONARIM HAKEDİŞLERİ'' 
WHEN 36 THEN  ''F.ÖDENECEK VERGİ VE DİĞER HÜKÜMLÜKLER'' 
WHEN 37 THEN  ''G.BORÇ VE GİDER KARŞILIKLARI'' 
WHEN 38 THEN  ''H.GELECEK AYLARA AİD GELİRLER VE GİDER TAHAKUKLARI'' 
WHEN 39 THEN  ''J.DİĞER KISA VADELİ YABANCI KAYNAKLAR'' 
WHEN 40 THEN  ''A.MALİ BORÇLAR''
WHEN 42 THEN  ''B.TİCARİ BORÇLAR'' 
WHEN 43 THEN  ''C.DİĞER BORÇLAR'' 
WHEN 44 THEN  ''D.ALINAN AVANSLAR'' 
WHEN 47 THEN  ''E.BORÇ VE GİDER KARŞILIKLARI'' 
WHEN 48 THEN  ''F.GELECEK YILLARA AİD GELİRLER VE GİDER TAHAKUKLARI'' 
WHEN 49 THEN  ''G.DİĞER UZUN VADELİ YABANCI KAYNAKLAR'' 
WHEN 50 THEN  ''A.ÖDENMİŞ SERMAYE''
WHEN 52 THEN  ''B.SERMAYE YEDEKLERİ''
WHEN 54 THEN  ''C.KAR YEDEKLERİ''
WHEN 57 THEN  ''D.GEÇMİŞ YILLAR KARLARI''
WHEN 58 THEN  ''E.GEÇMİŞ YILLAR ZARARLARI''
WHEN 59 THEN  ''F.DÖNEM NET KARI (ZARARI)''
ELSE ''DİĞER'' END  as Tip3,
CASE  EMFLINE.KEBIRCODE 
WHEN	100	 THEN	''     01. Kasa''
WHEN	101	 THEN	''     02. Alınan Çekler''
WHEN	102	 THEN	''     03. Banka''
WHEN	103	 THEN	''     04. Verilen Çekler ve Ödeme Emirleri (-)''
WHEN	108	 THEN	''     05. Diğer Hazır Değerler''
WHEN	110	 THEN	''     01. Hisse Senetleri              ''
WHEN	111	 THEN	''     02. Özel Kesim Tahvil, Senet ve Bonoları''
WHEN	112	 THEN	''     03. Kamu Kesimi Tahvil, Senet ve Bonoları      ''
WHEN	118	 THEN	''     04. Diğer Menkul Kıymetler ''
WHEN	119	 THEN	''     05. Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)''
WHEN	120	 THEN	''     01. Alıcılar''
WHEN	121	 THEN	''     02. Alacak Senetleri''
WHEN	122	 THEN	''     03. Alacak Senetleri Reeskontu (-)''
WHEN	126	 THEN	''     04. Verilen Depozito ve Teminatlar''
WHEN	127	 THEN	''     05. Diğer Ticari Alacaklar''
WHEN	128	 THEN	''     06. Şüpheli Ticari Alacaklar''
WHEN	129	 THEN	''     07. Şüpheli Ticari Alacaklar Karşılığı (-)''
WHEN	131	 THEN	''     01. Ortaklardan Alacaklar''
WHEN	132	 THEN	''     02. İştiraklerden Alacaklar''
WHEN	133	 THEN	''     03. Bağlı Ortaklıklardan Alacaklar''
WHEN	135	 THEN	''     04. Personelden Alacaklar ''
WHEN	136	 THEN	''     05. Diğer Çeşitli Alacaklar''
WHEN	137	 THEN	''     06. Diğer Alacak Senetleri Reeskontu (-)''
WHEN	138	 THEN	''     07. Şüpheli Diğer Alacaklar''
WHEN	139	 THEN	''     08. Şüpheli Diğer Alacaklar Karşılığı (-)''
WHEN	150	 THEN	''     01. İlk Madde ve Malzeme''
WHEN	151	 THEN	''     02. Yarı Mamuller - Üretim''
WHEN	152	 THEN	''     03. Mamuller''
WHEN	153	 THEN	''     04. Ticari Mallar ''
WHEN	157	 THEN	''     05. Diğer Stoklar''
WHEN	158	 THEN	''     06. Stok Değer Düşüklüğü Karşılığı (-) ''
WHEN	159	 THEN	''     07. Verilen Sipariş Avansları''
WHEN	170	 THEN	''     01. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	171	 THEN	''     02. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	172	 THEN	''     03. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	173	 THEN	''     04. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	174	 THEN	''     05. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	175	 THEN	''     06. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	176	 THEN	''     07. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	177	 THEN	''     08. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	178	 THEN	''     09. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	179	 THEN	''     10. Taşeronlara Verilen Avanslar''
WHEN	180	 THEN	''     01. Gelecek Aylara Ait Giderler''
WHEN	181	 THEN	''     02. Gelir Tahakkukları''
WHEN	190	 THEN	''     01. Devreden KDV''
WHEN	191	 THEN	''     02. İndirilecek Katma Değer Vergisi''
WHEN	192	 THEN	''     03. Diğer Katma Değer Vergisi''
WHEN	193	 THEN	''     04. Peşin Ödenen Vergiler ve Fonlar''
WHEN	195	 THEN	''     05. İş Avansları''
WHEN	196	 THEN	''     06.  Personel Avansları''
WHEN	197	 THEN	''     07. Sayım ve Tesellüm Noksanları''
WHEN	198	 THEN	''     08. Diğer Çeşitli Dönen Varlıklar''
WHEN	199	 THEN	''     09. Diğer Dönen Varlıklar Karşılığı (-)''
WHEN	220	 THEN	''     01. Alıcılar''
WHEN	221	 THEN	''     02. Alacak Senetleri''
WHEN	222	 THEN	''     03. Alacak Senetleri Reeskontu (-)''
WHEN	226	 THEN	''     04. Verilen Depozito ve Teminatlar''
WHEN	229	 THEN	''     05. Şüpheli Alacaklar Karşılığı (-)''
WHEN	231	 THEN	''     01. Ortaklardan Alacaklar''
WHEN	232	 THEN	''     02. İştiraklerden Alacaklar''
WHEN	233	 THEN	''     03. Bağlı Ortaklıklardan Alacaklar''
WHEN	235	 THEN	''     04. Personelden Alacaklar''
WHEN	236	 THEN	''     05. Diğer Çeşitli Alacaklar''
WHEN	237	 THEN	''     06. Diğer Alacak Senetleri Reeskontu (-)''
WHEN	239	 THEN	''     07. Şüpheli Diğer Alacaklar Karşılığı (-)''
WHEN	240	 THEN	''     01. Bağlı Menkul Kıymetler''
WHEN	241	 THEN	''     02. Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)''
WHEN	242	 THEN	''     03. İştirakler''
WHEN	243	 THEN	''     04. İştiraklere Sermaye Taahhütleri (-)''
WHEN	244	 THEN	''     05. İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)''
WHEN	245	 THEN	''     06. Bağlı Ortaklıklar''
WHEN	246	 THEN	''     07. Bağlı Ortaklıklara Sermaye Taahhütleri (-)''
WHEN	247	 THEN	''     08. Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)''
WHEN	248	 THEN	''     09. Diğer Mali Duran Varlıklar''
WHEN	249	 THEN	''     10. Diğer Mali Duran Varlıklar Değer Düşüklüğü Karşılığı (-)''
WHEN	250	 THEN	''     01. Arazi ve Arsalar''
WHEN	251	 THEN	''     02. Yer Altı ve Yer Üstü Düzenleri''
WHEN	252	 THEN	''     03. Binalar''
WHEN	253	 THEN	''     04. Tesis, Makine ve Cihazlar''
WHEN	254	 THEN	''     05. Taşıtlar''
WHEN	255	 THEN	''     06. Demirbaşlar''
WHEN	256	 THEN	''     07. Diğer Maddi Duran Varlıklar''
WHEN	257	 THEN	''     08. Birikmiş Amortismanlar (-)''
WHEN	258	 THEN	''     09. Yapılmakta Olan Yatırımlar''
WHEN	259	 THEN	''     10. Verilen Avanslar''
WHEN	260	 THEN	''     01. Haklar''
WHEN	261	 THEN	''     02. Şerefiye''
WHEN	262	 THEN	''     03. Kuruluş ve Örgütlenme Giderleri''
WHEN	263	 THEN	''     04. Araştırma ve Geliştirme Giderleri''
WHEN	264	 THEN	''     05. Özel Maliyetler''
WHEN	267	 THEN	''     06. Diğer Maddi Olmayan Duran Varlıklar''
WHEN	268	 THEN	''     07. Birikmiş Amortismanlar (-)''
WHEN	269	 THEN	''     08. Verilen Avanslar''
WHEN	271	 THEN	''     01. Arama Giderleri''
WHEN	272	 THEN	''     02. Hazırlık ve Geliştirme Giderleri''
WHEN	277	 THEN	''     03. Diğer Özel Tükenmeye Tabi Varlıklar''
WHEN	278	 THEN	''     04. Birikmiş Tükenme Payları (-)''
WHEN	279	 THEN	''     05. Verilen Avanslar''
WHEN	280	 THEN	''     01. Gelecek Yıllara Ait Giderler''
WHEN	281	 THEN	''     02. Gelir Tahakkukları''
WHEN	291	 THEN	''     01. Gelecek Yıllarda İndirilecek Katma Değer Vergisi''
WHEN	292	 THEN	''     02. Diğer Katma Değer Vergisi''
WHEN	295	 THEN	''     03. Peşin Ödenen Vergiler ve Fonlar''
WHEN	297	 THEN	''     04. Diğer Çeşitli Duran Varlıklar''
WHEN	300	 THEN	''      01. Banka Kredileri''
WHEN	303	 THEN	''      02. Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri''
WHEN	304	 THEN	''      03. Tahvil Anapara Borç, Taksit ve Faizleri''
WHEN	305	 THEN	''      04. Çıkarılmış Bonolar ve Senetler''
WHEN	306	 THEN	''      05. Çıkarılmış Diğer Menkul Kıymetler''
WHEN	308	 THEN	''      06. Menkul Kıymetler İhraç Farkı (-)''
WHEN	309	 THEN	''      07. Diğer Mali Borçlar''
WHEN	320	 THEN	''      01. Satıcılar''
WHEN	321	 THEN	''      02. Borç Senetleri''
WHEN	322	 THEN	''      03. Borç Senetleri Reeskontu (-)''
WHEN	326	 THEN	''      04. Alınan Depozito ve Teminatlar''
WHEN	329	 THEN	''      05. Diğer Ticari Borçlar''
WHEN	331	 THEN	''      01. Ortaklara Borçlar''
WHEN	332	 THEN	''      02. İştiraklere Borçlar''
WHEN	333	 THEN	''      03. Bağlı Ortaklıklara Borçlar''
WHEN	335	 THEN	''      04. Personele Borçlar''
WHEN	336	 THEN	''      05. Diğer Çeşitli Borçlar''
WHEN	337	 THEN	''      06. Diğer Borç Senetleri Reeskontu (-)''
WHEN	340	 THEN	''      01. Alınan Sipariş Avansları''
WHEN	349	 THEN	''      02. Alınan Diğer Avanslar''
WHEN	350	 THEN	''      01. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	351	 THEN	''      02. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	352	 THEN	''      03. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	353	 THEN	''      04. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	354	 THEN	''      05. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	355	 THEN	''      06. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	356	 THEN	''      07. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	357	 THEN	''      08. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	358	 THEN	''      09. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	360	 THEN	''      01. Ödenecek Vegi ve Fonlar''
WHEN	361	 THEN	''      02. Ödenecek Sosyal Güvenlik Kesintileri''
WHEN	368	 THEN	''      03. Vadesi Geçmiş Ertelenmiş Veya Taksitlendirilmiş Vergi ve Diğer Yüküml.''
WHEN	369	 THEN	''      04. Ödenecek Diğer Yükümlülükler''
WHEN	370	 THEN	''      01. Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları''
WHEN	371	 THEN	''      02. Dönem Karının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)''
WHEN	372	 THEN	''      03. Kıdem Tazminatı Karşılığı''
WHEN	373	 THEN	''      04. Maliyet Giderleri Karşılığı''
WHEN	379	 THEN	''      05. Diğer Borç ve Gider Karşılıkları''
WHEN	380	 THEN	''      01. Gelecek Aylara Ait Gelirler''
WHEN	381	 THEN	''      02. Gider Tahakkukları''
WHEN	391	 THEN	''      01. Hesaplanan KDV''
WHEN	392	 THEN	''      02. Diğer KDV''
WHEN	393	 THEN	''      03. Merkez ve Şubeler Cari Hesabı''
WHEN	397	 THEN	''      04. Sayım ve Tesellüm Fazlaları''
WHEN	399	 THEN	''      05. Diğer Çeşitli Yabancı Kaynaklar''
WHEN	400	 THEN	''      01. Banka Kredileri''
WHEN	405	 THEN	''      02. Çıkarılmış Tahviller''
WHEN	407	 THEN	''      03. Çıkarılmış Diğer Menkul Kıymetler''
WHEN	408	 THEN	''      04. Menkul Kıymetler İhraç Farkı (-)''
WHEN	409	 THEN	''      05. Diğer Mali Borçlar''
WHEN	420	 THEN	''      01. Satıcılar''
WHEN	421	 THEN	''      02. Borç Senetleri''
WHEN	422	 THEN	''      03. Borç Senetleri Reeskontu (-)''
WHEN	426	 THEN	''      04. Alınan Depozito ve Teminatlar''
WHEN	429	 THEN	''      05. Diğer Ticari Borçlar''
WHEN	431	 THEN	''      01. Ortaklara Borçlar''
WHEN	432	 THEN	''      02. İştiraklere Borçlar''
WHEN	433	 THEN	''      03. Bağlı Ortaklıklara Borçlar''
WHEN	436	 THEN	''      04. Diğer Çeşitli Borçlar''
WHEN	437	 THEN	''      05. Diğer Borç Senetleri Reeskontu (-)''
WHEN	438	 THEN	''      06. Kamuya Olan Ertelenmiş Veya Taksitlendirilmiş Borçlar''
WHEN	472	 THEN	''      01. Kıdem Tazminatı Karşılığı''
WHEN	479	 THEN	''      02. Diğer Borç ve Gider Karşılıkları''
WHEN	480	 THEN	''      01. Gelecek Yıllara Ait Gelirler''
WHEN	481	 THEN	''      02. Gider Tahakkukları''
WHEN	492	 THEN	''      01. Gelecek Yıllara Ertelenen Veya Terkin Edilen Katma Değer Vergisi''
WHEN	493	 THEN	''      02. Tesise Katılma Payları''
WHEN	499	 THEN	''      03. Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar''
WHEN	500	 THEN	''      01. Sermaye''
WHEN	501	 THEN	''      02. Ödenmemiş Sermaye (-)''
WHEN	520	 THEN	''      01. Hisse Senetleri İhraç Primleri''
WHEN	521	 THEN	''      02. Hisse Senedi İptal Karları''
WHEN	522	 THEN	''      03. M.D.V. Yeniden Değerleme Artışları''
WHEN	523	 THEN	''      04. İştirakler Yeniden Değerleme Artışları''
WHEN	529	 THEN	''      05. Diğer Sermaye Yedekleri''
WHEN	540	 THEN	''      01. Yasal Yedekler''
WHEN	541	 THEN	''      02. Statü Yedekleri''
WHEN	542	 THEN	''      03. Olağanüstü Yedekler''
WHEN	548	 THEN	''      04. Diğer Kar Yedekleri''
WHEN	549	 THEN	''      05. Özel Fonlar''
WHEN	570	 THEN	''    D GEÇMİŞ YILLAR KARLARI''
WHEN	580	 THEN	''    E GEÇMİŞ YILLAR ZARARLARI (-)''
WHEN	590	 THEN	''      01. Dönem Net Karı''
WHEN	591	 THEN	''      02. Dönem Net Zararı (-)''




ELSE ''DİĞER'' END Tip4, 
EMUHACC.code as [Hesap Kodu],EMUHACC.DEFINITION_ as [Hesap Adı],
ROUND(SUM(EMFLINE.DEBIT - EMFLINE.CREDIT),2) as [Değer]

from 


{DATABASE}LG_{FIRMA}_{DONEM}_EMFICHE EMFICHE,{DATABASE}LG_{FIRMA}_{DONEM}_EMFLINE EMFLINE,{DATABASE}LG_{FIRMA}_EMUHACC EMUHACC

WHERE

EMFICHE.LOGICALREF=EMFLINE.ACCFICHEREF  AND  EMFLINE.ACCOUNTREF=EMUHACC.LOGICALREF    AND SUBSTRING(EMFLINE.KEBIRCODE,1,1)<6

AND (EMFLINE.DATE_  BETWEEN @_BASTAR AND @_BITTAR)
GROUP BY  EMFLINE.KEBIRCODE,EMUHACC.code,EMUHACC.DEFINITION_ 


', 1, 4000)
     SET @QUERY2 = SUBSTRING('select
CASE WHEN SUBSTRING(EMFLINE.KEBIRCODE,1,1)<3 THEN  ''Aktif Varlıklar''  ELSE ''Pasif Varlıklar'' END as Tip1, 
CASE WHEN SUBSTRING(EMFLINE.KEBIRCODE,1,1)=1 THEN  ''I.DÖNEN VARLIKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=2) THEN  ''II.DURAN VARLIKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=3) THEN  ''I.KISA VADELİ YABANCI KAYNAKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=4) THEN  ''II.UZUN VADELİ YABANCI KAYNAKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=5) THEN  ''III.ÖZ KAYNAKLAR''  ELSE ''DİĞER'' END ) END ) END ) END ) END as Tip2, 
CASE  SUBSTRING(EMFLINE.KEBIRCODE,1,2) WHEN 10 THEN  ''A.HAZIR DEĞERLER''  
WHEN 11 THEN  ''B.MENKUL KIYMETLER''  
WHEN 12 THEN  ''C.TİCARİ ALACAKLAR''  
WHEN 13 THEN  ''D.DİĞER ALACAKLAR''  
WHEN 15 THEN  ''E.STOKLAR'' 
WHEN 17 THEN  ''F.YILLARA YAYGIN İNŞAAT VE ONARIM MALİYETLERİ'' 
WHEN 18 THEN  ''G.GELECEK AYLARA AİT GİDERLER VE GELİR TAHAKUKLARI'' 
WHEN 19 THEN  ''H.DİĞER DÖNEN VARLIKLAR'' 
WHEN 22 THEN  ''A.TİCARİ ALACAKLAR''
WHEN 23 THEN  ''B.DİĞER ALACAKLAR''
WHEN 24 THEN  ''C.MALİ DURAN VARLIKLAR''
WHEN 25 THEN  ''D.MADDİ DURAN VARLIKLAR''
WHEN 26 THEN  ''E.MADDİ OLMAYAN DURAN VARLIKLAR''
WHEN 27 THEN  ''F.ÖZEL TÜKENMEYE TABİ VARLIKLAR ''
WHEN 28 THEN  ''G.GELECEK YILLARA AİD GİDERLER VE GELİR TAHAKUKLARI''  
WHEN 29 THEN  ''H.DİĞER DURAN VARLIKLAR'' 
WHEN 30 THEN  ''A.MALİ BORÇLAR''
WHEN 32 THEN  ''B.TİCARİ BORÇLAR'' 
WHEN 33 THEN  ''C.DİĞER BORÇLAR'' 
WHEN 34 THEN  ''D.ALINAN AVANSLAR'' 
WHEN 35 THEN  ''E.YILLARA YAYGIN İNŞAAT VE ONARIM HAKEDİŞLERİ'' 
WHEN 36 THEN  ''F.ÖDENECEK VERGİ VE DİĞER HÜKÜMLÜKLER'' 
WHEN 37 THEN  ''G.BORÇ VE GİDER KARŞILIKLARI'' 
WHEN 38 THEN  ''H.GELECEK AYLARA AİD GELİRLER VE GİDER TAHAKUKLARI'' 
WHEN 39 THEN  ''J.DİĞER KISA VADELİ YABANCI KAYNAKLAR'' 
WHEN 40 THEN  ''A.MALİ BORÇLAR''
WHEN 42 THEN  ''B.TİCARİ BORÇLAR'' 
WHEN 43 THEN  ''C.DİĞER BORÇLAR'' 
WHEN 44 THEN  ''D.ALINAN AVANSLAR'' 
WHEN 47 THEN  ''E.BORÇ VE GİDER KARŞILIKLARI'' 
WHEN 48 THEN  ''F.GELECEK YILLARA AİD GELİRLER VE GİDER TAHAKUKLARI'' 
WHEN 49 THEN  ''G.DİĞER UZUN VADELİ YABANCI KAYNAKLAR'' 
WHEN 50 THEN  ''A.ÖDENMİŞ SERMAYE''
WHEN 52 THEN  ''B.SERMAYE YEDEKLERİ''
WHEN 54 THEN  ''C.KAR YEDEKLERİ''
WHEN 57 THEN  ''D.GEÇMİŞ YILLAR KARLARI''
WHEN 58 THEN  ''E.GEÇMİŞ YILLAR ZARARLARI''
WHEN 59 THEN  ''F.DÖNEM NET KARI (ZARARI)''
ELSE ''DİĞER'' END  as Tip3,
CASE  EMFLINE.KEBIRCODE 
WHEN	100	 THEN	''     01. Kasa''
WHEN	101	 THEN	''     02. Alınan Çekler''
WHEN	102	 THEN	''     03. Banka''
WHEN	103	 THEN	''     04. Verilen Çekler ve Ödeme Emirleri (-)''
WHEN	108	 THEN	''     05. Diğer Hazır Değerler''
WHEN	110	 THEN	''     01. Hisse Senetleri              ''
WHEN	111	 THEN	''     02. Özel Kesim Tahvil, Senet ve Bonoları''
WHEN	112	 THEN	''     03. Kamu Kesimi Tahvil, Senet ve Bonoları      ''
WHEN	118	 THEN	''     04. Diğer Menkul Kıymetler ''
WHEN	119	 THEN	''     05. Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)''
WHEN	120	 THEN	''     01. Alıcılar''
WHEN	121	 THEN	''     02. Alacak Senetleri''
WHEN	122	 THEN	''     03. Alacak Senetleri Reeskontu (-)''
WHEN	126	 THEN	''     04. Verilen Depozito ve Teminatlar''
WHEN	127	 THEN	''     05. Diğer Ticari Alacaklar''
WHEN	128	 THEN	''     06. Şüpheli Ticari Alacaklar''
WHEN	129	 THEN	''     07. Şüpheli Ticari Alacaklar Karşılığı (-)''
WHEN	131	 THEN	''     01. Ortaklardan Alacaklar''
WHEN	132	 THEN	''     02. İştiraklerden Alacaklar''
WHEN	133	 THEN	''     03. Bağlı Ortaklıklardan Alacaklar''
WHEN	135	 THEN	''     04. Personelden Alacaklar ''
WHEN	136	 THEN	''     05. Diğer Çeşitli Alacaklar''
WHEN	137	 THEN	''     06. Diğer Alacak Senetleri Reeskontu (-)''
WHEN	138	 THEN	''     07. Şüpheli Diğer Alacaklar''
WHEN	139	 THEN	''     08. Şüpheli Diğer Alacaklar Karşılığı (-)''
WHEN	150	 THEN	''     01. İlk Madde ve Malzeme''
WHEN	151	 THEN	''     02. Yarı Mamuller - Üretim''
WHEN	152	 THEN	''     03. Mamuller''
WHEN	153	 THEN	''     04. Ticari Mallar ''
WHEN	157	 THEN	''     05. Diğer Stoklar''
WHEN	158	 THEN	''     06. Stok Değer Düşüklüğü Karşılığı (-) ''
WHEN	159	 THEN	''     07. Verilen Sipariş Avansları''
WHEN	170	 THEN	''     01. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	171	 THEN	''     02. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	172	 THEN	''     03. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	173	 THEN	''     04. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	174	 THEN	''     05. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	175	 THEN	''     06. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	176	 THEN	''     07. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	177	 THEN	''     08. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	178	 THEN	''     09. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	179	 THEN	''     10. Taşeronlara Verilen Avanslar''
WHEN	180	 THEN	''     01. Gelecek Aylara Ait Giderler''
WHEN	181	 THEN	''     02. Gelir Tahakkukları''
WHEN	190	 THEN	''     01. Devreden KDV''
WHEN	191	 THEN	''     02. İndirilecek Katma Değer Vergisi''
WHEN	192	 THEN	''     03. Diğer Katma Değer Vergisi''
WHEN	193	 THEN	''     04. Peşin Ödenen Vergiler ve Fonlar''
WHEN	195	 THEN	''     05. İş Avansları''
WHEN	196	 THEN	''     06.  Personel Avansları''
WHEN	197	 THEN	''     07. Sayım ve Tesellüm Noksanları''
WHEN	198	 THEN	''     08. Diğer Çeşitli Dönen Varlıklar''
WHEN	199	 THEN	''     09. Diğer Dönen Varlıklar Karşılığı (-)''
WHEN	220	 THEN	''     01. Alıcılar''
WHEN	221	 THEN	''     02. Alacak Senetleri''
WHEN	222	 THEN	''     03. Alacak Senetleri Reeskontu (-)''
WHEN	226	 THEN	''     04. Verilen Depozito ve Teminatlar''
WHEN	229	 THEN	''     05. Şüpheli Alacaklar Karşılığı (-)''
WHEN	231	 THEN	''     01. Ortaklardan Alacaklar''
WHEN	232	 THEN	''     02. İştiraklerden Alacaklar''
WHEN	233	 THEN	''     03. Bağlı Ortaklıklardan Alacaklar''
WHEN	235	 THEN	''     04. Personelden Alacaklar''
WHEN	236	 THEN	''     05. Diğer Çeşitli Alacaklar''
WHEN	237	 THEN	''     06. Diğer Alacak Senetleri Reeskontu (-)''
WHEN	239	 THEN	''     07. Şüpheli Diğer Alacaklar Karşılığı (-)''
WHEN	240	 THEN	''     01. Bağlı Menkul Kıymetler''
WHEN	241	 THEN	''     02. Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)''
WHEN	242	 THEN	''     03. İştirakler''
WHEN	243	 THEN	''     04. İştiraklere Sermaye Taahhütleri (-)''
WHEN	244	 THEN	''     05. İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)''
WHEN	245	 THEN	''     06. Bağlı Ortaklıklar''
WHEN	246	 THEN	''     07. Bağlı Ortaklıklara Sermaye Taahhütleri (-)''
WHEN	247	 THEN	''     08. Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)''
WHEN	248	 THEN	''     09. Diğer Mali Duran Varlıklar''
WHEN	249	 THEN	''     10. Diğer Mali Duran Varlıklar Değer Düşüklüğü Karşılığı (-)''
WHEN	250	 THEN	''     01. Arazi ve Arsalar''
WHEN	251	 THEN	''     02. Yer Altı ve Yer Üstü Düzenleri''
WHEN	252	 THEN	''     03. Binalar''
WHEN	253	 THEN	''     04. Tesis, Makine ve Cihazlar''
WHEN	254	 THEN	''     05. Taşıtlar''
WHEN	255	 THEN	''     06. Demirbaşlar''
WHEN	256	 THEN	''     07. Diğer Maddi Duran Varlıklar''
WHEN	257	 THEN	''     08. Birikmiş Amortismanlar (-)''
WHEN	258	 THEN	''     09. Yapılmakta Olan Yatırımlar''
WHEN	259	 THEN	''     10. Verilen Avanslar''
WHEN	260	 THEN	''     01. Haklar''
WHEN	261	 THEN	''     02. Şerefiye''
WHEN	262	 THEN	''     03. Kuruluş ve Örgütlenme Giderleri''
WHEN	263	 THEN	''     04. Araştırma ve Geliştirme Giderleri''
WHEN	264	 THEN	''     05. Özel Maliyetler''
WHEN	267	 THEN	''     06. Diğer Maddi Olmayan Duran Varlıklar''
WHEN	268	 THEN	''     07. Birikmiş Amortismanlar (-)''
WHEN	269	 THEN	''     08. Verilen Avanslar''
WHEN	271	 THEN	''     01. Arama Giderleri''
WHEN	272	 THEN	''     02. Hazırlık ve Geliştirme Giderleri''
WHEN	277	 THEN	''     03. Diğer Özel Tükenmeye Tabi Varlıklar''
WHEN	278	 THEN	''     04. Birikmiş Tükenme Payları (-)''
WHEN	279	 THEN	''     05. Verilen Avanslar''
WHEN	280	 THEN	''     01. Gelecek Yıllara Ait Giderler''
WHEN	281	 THEN	''     02. Gelir Tahakkukları''
WHEN	291	 THEN	''     01. Gelecek Yıllarda İndirilecek Katma Değer Vergisi''
WHEN	292	 THEN	''     02. Diğer Katma Değer Vergisi''
WHEN	295	 THEN	''     03. Peşin Ödenen Vergiler ve Fonlar''
WHEN	297	 THEN	''     04. Diğer Çeşitli Duran Varlıklar''
WHEN	300	 THEN	''      01. Banka Kredileri''
WHEN	303	 THEN	''      02. Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri''
WHEN	304	 THEN	''      03. Tahvil Anapara Borç, Taksit ve Faizleri''
WHEN	305	 THEN	''      04. Çıkarılmış Bonolar ve Senetler''
WHEN	306	 THEN	''      05. Çıkarılmış Diğer Menkul Kıymetler''
WHEN	308	 THEN	''      06. Menkul Kıymetler İhraç Farkı (-)''
WHEN	309	 THEN	''      07. Diğer Mali Borçlar''
WHEN	320	 THEN	''      01. Satıcılar''
WHEN	321	 THEN	''      02. Borç Senetleri''
WHEN	322	 THEN	''      03. Borç Senetleri Reeskontu (-)''
WHEN	326	 THEN	''      04. Alınan Depozito ve Teminatlar''
WHEN	329	 THEN	''      05. Diğer Ticari Borçlar''
WHEN	331	 THEN	''      01. Ortaklara Borçlar''
WHEN	332	 THEN	''      02. İştiraklere Borçlar''
WHEN	333	 THEN	''      03. Bağlı Ortaklıklara Borçlar''
WHEN	335	 THEN	''      04. Personele Borçlar''
WHEN	336	 THEN	''      05. Diğer Çeşitli Borçlar''
WHEN	337	 THEN	''      06. Diğer Borç Senetleri Reeskontu (-)''
WHEN	340	 THEN	''      01. Alınan Sipariş Avansları''
WHEN	349	 THEN	''      02. Alınan Diğer Avanslar''
WHEN	350	 THEN	''      01. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	351	 THEN	''      02. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	352	 THEN	''      03. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	353	 THEN	''      04. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	354	 THEN	''      05. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	355	 THEN	''      06. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	356	 THEN	''      07. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	357	 THEN	''      08. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	358	 THEN	''      09. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	360	 THEN	''      01. Ödenecek Vegi ve Fonlar''
WHEN	361	 THEN	''      02. Ödenecek Sosyal Güvenlik Kesintileri''
WHEN	368	 THEN	''      03. Vadesi Geçmiş Ertelenmiş Veya Taksitlendirilmiş Vergi ve Diğer Yüküml.''
WHEN	369	 THEN	''      04. Ödenecek Diğer Yükümlülükler''
WHEN	370	 THEN	''      01. Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları''
WHEN	371	 THEN	''      02. Dönem Karının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)''
WHEN	372	 THEN	''      03. Kıdem Tazminatı Karşılığı''
WHEN	373	 THEN	''      04. Maliyet Giderleri Karşılığı''
WHEN	379	 THEN	''      05. Diğer Borç ve Gider Karşılıkları''
WHEN	380	 THEN	''      01. Gelecek Aylara Ait Gelirler''
WHEN	381	 THEN	''      02. Gider Tahakkukları''
WHEN	391	 THEN	''      01. Hesaplanan KDV''
WHEN	392	 THEN	''      02. Diğer KDV''
WHEN	393	 THEN	''      03. Merkez ve Şubeler Cari Hesabı''
WHEN	397	 THEN	''      04. Sayım ve Tesellüm Fazlaları''
WHEN	399	 THEN	''      05. Diğer Çeşitli Yabancı Kaynaklar''
WHEN	400	 THEN	''      01. Banka Kredileri''
WHEN	405	 THEN	''      02. Çıkarılmış Tahviller''
WHEN	407	 THEN	''      03. Çıkarılmış Diğer Menkul Kıymetler''
WHEN	408	 THEN	''      04. Menkul Kıymetler İhraç Farkı (-)''
WHEN	409	 THEN	''      05. Diğer Mali Borçlar''
WHEN	420	 THEN	''      01. Satıcılar''
WHEN	421	 THEN	''      02. Borç Senetleri''
WHEN	422	 THEN	''      03. Borç Senetleri Reeskontu (-)''
WHEN	426	 THEN	''      04. Alınan Depozito ve Teminatlar''
WHEN	429	 THEN	''      05. Diğer Ticari Borçlar''
WHEN	431	 THEN	''      01. Ortaklara Borçlar''
WHEN	432	 THEN	''      02. İştiraklere Borçlar''
WHEN	433	 THEN	''      03. Bağlı Ortaklıklara Borçlar''
WHEN	436	 THEN	''      04. Diğer Çeşitli Borçlar''
WHEN	437	 THEN	''      05. Diğer Borç Senetleri Reeskontu (-)''
WHEN	438	 THEN	''      06. Kamuya Olan Ertelenmiş Veya Taksitlendirilmiş Borçlar''
WHEN	472	 THEN	''      01. Kıdem Tazminatı Karşılığı''
WHEN	479	 THEN	''      02. Diğer Borç ve Gider Karşılıkları''
WHEN	480	 THEN	''      01. Gelecek Yıllara Ait Gelirler''
WHEN	481	 THEN	''      02. Gider Tahakkukları''
WHEN	492	 THEN	''      01. Gelecek Yıllara Ertelenen Veya Terkin Edilen Katma Değer Vergisi''
WHEN	493	 THEN	''      02. Tesise Katılma Payları''
WHEN	499	 THEN	''      03. Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar''
WHEN	500	 THEN	''      01. Sermaye''
WHEN	501	 THEN	''      02. Ödenmemiş Sermaye (-)''
WHEN	520	 THEN	''      01. Hisse Senetleri İhraç Primleri''
WHEN	521	 THEN	''      02. Hisse Senedi İptal Karları''
WHEN	522	 THEN	''      03. M.D.V. Yeniden Değerleme Artışları''
WHEN	523	 THEN	''      04. İştirakler Yeniden Değerleme Artışları''
WHEN	529	 THEN	''      05. Diğer Sermaye Yedekleri''
WHEN	540	 THEN	''      01. Yasal Yedekler''
WHEN	541	 THEN	''      02. Statü Yedekleri''
WHEN	542	 THEN	''      03. Olağanüstü Yedekler''
WHEN	548	 THEN	''      04. Diğer Kar Yedekleri''
WHEN	549	 THEN	''      05. Özel Fonlar''
WHEN	570	 THEN	''    D GEÇMİŞ YILLAR KARLARI''
WHEN	580	 THEN	''    E GEÇMİŞ YILLAR ZARARLARI (-)''
WHEN	590	 THEN	''      01. Dönem Net Karı''
WHEN	591	 THEN	''      02. Dönem Net Zararı (-)''




ELSE ''DİĞER'' END Tip4, 
EMUHACC.code as [Hesap Kodu],EMUHACC.DEFINITION_ as [Hesap Adı],
ROUND(SUM(EMFLINE.DEBIT - EMFLINE.CREDIT),2) as [Değer]

from 


{DATABASE}LG_{FIRMA}_{DONEM}_EMFICHE EMFICHE,{DATABASE}LG_{FIRMA}_{DONEM}_EMFLINE EMFLINE,{DATABASE}LG_{FIRMA}_EMUHACC EMUHACC

WHERE

EMFICHE.LOGICALREF=EMFLINE.ACCFICHEREF  AND  EMFLINE.ACCOUNTREF=EMUHACC.LOGICALREF    AND SUBSTRING(EMFLINE.KEBIRCODE,1,1)<6

AND (EMFLINE.DATE_  BETWEEN @_BASTAR AND @_BITTAR)
GROUP BY  EMFLINE.KEBIRCODE,EMUHACC.code,EMUHACC.DEFINITION_ 


', 4001, 4000)
     SET @QUERY3 = SUBSTRING('select
CASE WHEN SUBSTRING(EMFLINE.KEBIRCODE,1,1)<3 THEN  ''Aktif Varlıklar''  ELSE ''Pasif Varlıklar'' END as Tip1, 
CASE WHEN SUBSTRING(EMFLINE.KEBIRCODE,1,1)=1 THEN  ''I.DÖNEN VARLIKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=2) THEN  ''II.DURAN VARLIKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=3) THEN  ''I.KISA VADELİ YABANCI KAYNAKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=4) THEN  ''II.UZUN VADELİ YABANCI KAYNAKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=5) THEN  ''III.ÖZ KAYNAKLAR''  ELSE ''DİĞER'' END ) END ) END ) END ) END as Tip2, 
CASE  SUBSTRING(EMFLINE.KEBIRCODE,1,2) WHEN 10 THEN  ''A.HAZIR DEĞERLER''  
WHEN 11 THEN  ''B.MENKUL KIYMETLER''  
WHEN 12 THEN  ''C.TİCARİ ALACAKLAR''  
WHEN 13 THEN  ''D.DİĞER ALACAKLAR''  
WHEN 15 THEN  ''E.STOKLAR'' 
WHEN 17 THEN  ''F.YILLARA YAYGIN İNŞAAT VE ONARIM MALİYETLERİ'' 
WHEN 18 THEN  ''G.GELECEK AYLARA AİT GİDERLER VE GELİR TAHAKUKLARI'' 
WHEN 19 THEN  ''H.DİĞER DÖNEN VARLIKLAR'' 
WHEN 22 THEN  ''A.TİCARİ ALACAKLAR''
WHEN 23 THEN  ''B.DİĞER ALACAKLAR''
WHEN 24 THEN  ''C.MALİ DURAN VARLIKLAR''
WHEN 25 THEN  ''D.MADDİ DURAN VARLIKLAR''
WHEN 26 THEN  ''E.MADDİ OLMAYAN DURAN VARLIKLAR''
WHEN 27 THEN  ''F.ÖZEL TÜKENMEYE TABİ VARLIKLAR ''
WHEN 28 THEN  ''G.GELECEK YILLARA AİD GİDERLER VE GELİR TAHAKUKLARI''  
WHEN 29 THEN  ''H.DİĞER DURAN VARLIKLAR'' 
WHEN 30 THEN  ''A.MALİ BORÇLAR''
WHEN 32 THEN  ''B.TİCARİ BORÇLAR'' 
WHEN 33 THEN  ''C.DİĞER BORÇLAR'' 
WHEN 34 THEN  ''D.ALINAN AVANSLAR'' 
WHEN 35 THEN  ''E.YILLARA YAYGIN İNŞAAT VE ONARIM HAKEDİŞLERİ'' 
WHEN 36 THEN  ''F.ÖDENECEK VERGİ VE DİĞER HÜKÜMLÜKLER'' 
WHEN 37 THEN  ''G.BORÇ VE GİDER KARŞILIKLARI'' 
WHEN 38 THEN  ''H.GELECEK AYLARA AİD GELİRLER VE GİDER TAHAKUKLARI'' 
WHEN 39 THEN  ''J.DİĞER KISA VADELİ YABANCI KAYNAKLAR'' 
WHEN 40 THEN  ''A.MALİ BORÇLAR''
WHEN 42 THEN  ''B.TİCARİ BORÇLAR'' 
WHEN 43 THEN  ''C.DİĞER BORÇLAR'' 
WHEN 44 THEN  ''D.ALINAN AVANSLAR'' 
WHEN 47 THEN  ''E.BORÇ VE GİDER KARŞILIKLARI'' 
WHEN 48 THEN  ''F.GELECEK YILLARA AİD GELİRLER VE GİDER TAHAKUKLARI'' 
WHEN 49 THEN  ''G.DİĞER UZUN VADELİ YABANCI KAYNAKLAR'' 
WHEN 50 THEN  ''A.ÖDENMİŞ SERMAYE''
WHEN 52 THEN  ''B.SERMAYE YEDEKLERİ''
WHEN 54 THEN  ''C.KAR YEDEKLERİ''
WHEN 57 THEN  ''D.GEÇMİŞ YILLAR KARLARI''
WHEN 58 THEN  ''E.GEÇMİŞ YILLAR ZARARLARI''
WHEN 59 THEN  ''F.DÖNEM NET KARI (ZARARI)''
ELSE ''DİĞER'' END  as Tip3,
CASE  EMFLINE.KEBIRCODE 
WHEN	100	 THEN	''     01. Kasa''
WHEN	101	 THEN	''     02. Alınan Çekler''
WHEN	102	 THEN	''     03. Banka''
WHEN	103	 THEN	''     04. Verilen Çekler ve Ödeme Emirleri (-)''
WHEN	108	 THEN	''     05. Diğer Hazır Değerler''
WHEN	110	 THEN	''     01. Hisse Senetleri              ''
WHEN	111	 THEN	''     02. Özel Kesim Tahvil, Senet ve Bonoları''
WHEN	112	 THEN	''     03. Kamu Kesimi Tahvil, Senet ve Bonoları      ''
WHEN	118	 THEN	''     04. Diğer Menkul Kıymetler ''
WHEN	119	 THEN	''     05. Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)''
WHEN	120	 THEN	''     01. Alıcılar''
WHEN	121	 THEN	''     02. Alacak Senetleri''
WHEN	122	 THEN	''     03. Alacak Senetleri Reeskontu (-)''
WHEN	126	 THEN	''     04. Verilen Depozito ve Teminatlar''
WHEN	127	 THEN	''     05. Diğer Ticari Alacaklar''
WHEN	128	 THEN	''     06. Şüpheli Ticari Alacaklar''
WHEN	129	 THEN	''     07. Şüpheli Ticari Alacaklar Karşılığı (-)''
WHEN	131	 THEN	''     01. Ortaklardan Alacaklar''
WHEN	132	 THEN	''     02. İştiraklerden Alacaklar''
WHEN	133	 THEN	''     03. Bağlı Ortaklıklardan Alacaklar''
WHEN	135	 THEN	''     04. Personelden Alacaklar ''
WHEN	136	 THEN	''     05. Diğer Çeşitli Alacaklar''
WHEN	137	 THEN	''     06. Diğer Alacak Senetleri Reeskontu (-)''
WHEN	138	 THEN	''     07. Şüpheli Diğer Alacaklar''
WHEN	139	 THEN	''     08. Şüpheli Diğer Alacaklar Karşılığı (-)''
WHEN	150	 THEN	''     01. İlk Madde ve Malzeme''
WHEN	151	 THEN	''     02. Yarı Mamuller - Üretim''
WHEN	152	 THEN	''     03. Mamuller''
WHEN	153	 THEN	''     04. Ticari Mallar ''
WHEN	157	 THEN	''     05. Diğer Stoklar''
WHEN	158	 THEN	''     06. Stok Değer Düşüklüğü Karşılığı (-) ''
WHEN	159	 THEN	''     07. Verilen Sipariş Avansları''
WHEN	170	 THEN	''     01. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	171	 THEN	''     02. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	172	 THEN	''     03. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	173	 THEN	''     04. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	174	 THEN	''     05. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	175	 THEN	''     06. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	176	 THEN	''     07. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	177	 THEN	''     08. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	178	 THEN	''     09. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	179	 THEN	''     10. Taşeronlara Verilen Avanslar''
WHEN	180	 THEN	''     01. Gelecek Aylara Ait Giderler''
WHEN	181	 THEN	''     02. Gelir Tahakkukları''
WHEN	190	 THEN	''     01. Devreden KDV''
WHEN	191	 THEN	''     02. İndirilecek Katma Değer Vergisi''
WHEN	192	 THEN	''     03. Diğer Katma Değer Vergisi''
WHEN	193	 THEN	''     04. Peşin Ödenen Vergiler ve Fonlar''
WHEN	195	 THEN	''     05. İş Avansları''
WHEN	196	 THEN	''     06.  Personel Avansları''
WHEN	197	 THEN	''     07. Sayım ve Tesellüm Noksanları''
WHEN	198	 THEN	''     08. Diğer Çeşitli Dönen Varlıklar''
WHEN	199	 THEN	''     09. Diğer Dönen Varlıklar Karşılığı (-)''
WHEN	220	 THEN	''     01. Alıcılar''
WHEN	221	 THEN	''     02. Alacak Senetleri''
WHEN	222	 THEN	''     03. Alacak Senetleri Reeskontu (-)''
WHEN	226	 THEN	''     04. Verilen Depozito ve Teminatlar''
WHEN	229	 THEN	''     05. Şüpheli Alacaklar Karşılığı (-)''
WHEN	231	 THEN	''     01. Ortaklardan Alacaklar''
WHEN	232	 THEN	''     02. İştiraklerden Alacaklar''
WHEN	233	 THEN	''     03. Bağlı Ortaklıklardan Alacaklar''
WHEN	235	 THEN	''     04. Personelden Alacaklar''
WHEN	236	 THEN	''     05. Diğer Çeşitli Alacaklar''
WHEN	237	 THEN	''     06. Diğer Alacak Senetleri Reeskontu (-)''
WHEN	239	 THEN	''     07. Şüpheli Diğer Alacaklar Karşılığı (-)''
WHEN	240	 THEN	''     01. Bağlı Menkul Kıymetler''
WHEN	241	 THEN	''     02. Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)''
WHEN	242	 THEN	''     03. İştirakler''
WHEN	243	 THEN	''     04. İştiraklere Sermaye Taahhütleri (-)''
WHEN	244	 THEN	''     05. İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)''
WHEN	245	 THEN	''     06. Bağlı Ortaklıklar''
WHEN	246	 THEN	''     07. Bağlı Ortaklıklara Sermaye Taahhütleri (-)''
WHEN	247	 THEN	''     08. Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)''
WHEN	248	 THEN	''     09. Diğer Mali Duran Varlıklar''
WHEN	249	 THEN	''     10. Diğer Mali Duran Varlıklar Değer Düşüklüğü Karşılığı (-)''
WHEN	250	 THEN	''     01. Arazi ve Arsalar''
WHEN	251	 THEN	''     02. Yer Altı ve Yer Üstü Düzenleri''
WHEN	252	 THEN	''     03. Binalar''
WHEN	253	 THEN	''     04. Tesis, Makine ve Cihazlar''
WHEN	254	 THEN	''     05. Taşıtlar''
WHEN	255	 THEN	''     06. Demirbaşlar''
WHEN	256	 THEN	''     07. Diğer Maddi Duran Varlıklar''
WHEN	257	 THEN	''     08. Birikmiş Amortismanlar (-)''
WHEN	258	 THEN	''     09. Yapılmakta Olan Yatırımlar''
WHEN	259	 THEN	''     10. Verilen Avanslar''
WHEN	260	 THEN	''     01. Haklar''
WHEN	261	 THEN	''     02. Şerefiye''
WHEN	262	 THEN	''     03. Kuruluş ve Örgütlenme Giderleri''
WHEN	263	 THEN	''     04. Araştırma ve Geliştirme Giderleri''
WHEN	264	 THEN	''     05. Özel Maliyetler''
WHEN	267	 THEN	''     06. Diğer Maddi Olmayan Duran Varlıklar''
WHEN	268	 THEN	''     07. Birikmiş Amortismanlar (-)''
WHEN	269	 THEN	''     08. Verilen Avanslar''
WHEN	271	 THEN	''     01. Arama Giderleri''
WHEN	272	 THEN	''     02. Hazırlık ve Geliştirme Giderleri''
WHEN	277	 THEN	''     03. Diğer Özel Tükenmeye Tabi Varlıklar''
WHEN	278	 THEN	''     04. Birikmiş Tükenme Payları (-)''
WHEN	279	 THEN	''     05. Verilen Avanslar''
WHEN	280	 THEN	''     01. Gelecek Yıllara Ait Giderler''
WHEN	281	 THEN	''     02. Gelir Tahakkukları''
WHEN	291	 THEN	''     01. Gelecek Yıllarda İndirilecek Katma Değer Vergisi''
WHEN	292	 THEN	''     02. Diğer Katma Değer Vergisi''
WHEN	295	 THEN	''     03. Peşin Ödenen Vergiler ve Fonlar''
WHEN	297	 THEN	''     04. Diğer Çeşitli Duran Varlıklar''
WHEN	300	 THEN	''      01. Banka Kredileri''
WHEN	303	 THEN	''      02. Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri''
WHEN	304	 THEN	''      03. Tahvil Anapara Borç, Taksit ve Faizleri''
WHEN	305	 THEN	''      04. Çıkarılmış Bonolar ve Senetler''
WHEN	306	 THEN	''      05. Çıkarılmış Diğer Menkul Kıymetler''
WHEN	308	 THEN	''      06. Menkul Kıymetler İhraç Farkı (-)''
WHEN	309	 THEN	''      07. Diğer Mali Borçlar''
WHEN	320	 THEN	''      01. Satıcılar''
WHEN	321	 THEN	''      02. Borç Senetleri''
WHEN	322	 THEN	''      03. Borç Senetleri Reeskontu (-)''
WHEN	326	 THEN	''      04. Alınan Depozito ve Teminatlar''
WHEN	329	 THEN	''      05. Diğer Ticari Borçlar''
WHEN	331	 THEN	''      01. Ortaklara Borçlar''
WHEN	332	 THEN	''      02. İştiraklere Borçlar''
WHEN	333	 THEN	''      03. Bağlı Ortaklıklara Borçlar''
WHEN	335	 THEN	''      04. Personele Borçlar''
WHEN	336	 THEN	''      05. Diğer Çeşitli Borçlar''
WHEN	337	 THEN	''      06. Diğer Borç Senetleri Reeskontu (-)''
WHEN	340	 THEN	''      01. Alınan Sipariş Avansları''
WHEN	349	 THEN	''      02. Alınan Diğer Avanslar''
WHEN	350	 THEN	''      01. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	351	 THEN	''      02. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	352	 THEN	''      03. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	353	 THEN	''      04. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	354	 THEN	''      05. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	355	 THEN	''      06. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	356	 THEN	''      07. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	357	 THEN	''      08. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	358	 THEN	''      09. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	360	 THEN	''      01. Ödenecek Vegi ve Fonlar''
WHEN	361	 THEN	''      02. Ödenecek Sosyal Güvenlik Kesintileri''
WHEN	368	 THEN	''      03. Vadesi Geçmiş Ertelenmiş Veya Taksitlendirilmiş Vergi ve Diğer Yüküml.''
WHEN	369	 THEN	''      04. Ödenecek Diğer Yükümlülükler''
WHEN	370	 THEN	''      01. Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları''
WHEN	371	 THEN	''      02. Dönem Karının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)''
WHEN	372	 THEN	''      03. Kıdem Tazminatı Karşılığı''
WHEN	373	 THEN	''      04. Maliyet Giderleri Karşılığı''
WHEN	379	 THEN	''      05. Diğer Borç ve Gider Karşılıkları''
WHEN	380	 THEN	''      01. Gelecek Aylara Ait Gelirler''
WHEN	381	 THEN	''      02. Gider Tahakkukları''
WHEN	391	 THEN	''      01. Hesaplanan KDV''
WHEN	392	 THEN	''      02. Diğer KDV''
WHEN	393	 THEN	''      03. Merkez ve Şubeler Cari Hesabı''
WHEN	397	 THEN	''      04. Sayım ve Tesellüm Fazlaları''
WHEN	399	 THEN	''      05. Diğer Çeşitli Yabancı Kaynaklar''
WHEN	400	 THEN	''      01. Banka Kredileri''
WHEN	405	 THEN	''      02. Çıkarılmış Tahviller''
WHEN	407	 THEN	''      03. Çıkarılmış Diğer Menkul Kıymetler''
WHEN	408	 THEN	''      04. Menkul Kıymetler İhraç Farkı (-)''
WHEN	409	 THEN	''      05. Diğer Mali Borçlar''
WHEN	420	 THEN	''      01. Satıcılar''
WHEN	421	 THEN	''      02. Borç Senetleri''
WHEN	422	 THEN	''      03. Borç Senetleri Reeskontu (-)''
WHEN	426	 THEN	''      04. Alınan Depozito ve Teminatlar''
WHEN	429	 THEN	''      05. Diğer Ticari Borçlar''
WHEN	431	 THEN	''      01. Ortaklara Borçlar''
WHEN	432	 THEN	''      02. İştiraklere Borçlar''
WHEN	433	 THEN	''      03. Bağlı Ortaklıklara Borçlar''
WHEN	436	 THEN	''      04. Diğer Çeşitli Borçlar''
WHEN	437	 THEN	''      05. Diğer Borç Senetleri Reeskontu (-)''
WHEN	438	 THEN	''      06. Kamuya Olan Ertelenmiş Veya Taksitlendirilmiş Borçlar''
WHEN	472	 THEN	''      01. Kıdem Tazminatı Karşılığı''
WHEN	479	 THEN	''      02. Diğer Borç ve Gider Karşılıkları''
WHEN	480	 THEN	''      01. Gelecek Yıllara Ait Gelirler''
WHEN	481	 THEN	''      02. Gider Tahakkukları''
WHEN	492	 THEN	''      01. Gelecek Yıllara Ertelenen Veya Terkin Edilen Katma Değer Vergisi''
WHEN	493	 THEN	''      02. Tesise Katılma Payları''
WHEN	499	 THEN	''      03. Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar''
WHEN	500	 THEN	''      01. Sermaye''
WHEN	501	 THEN	''      02. Ödenmemiş Sermaye (-)''
WHEN	520	 THEN	''      01. Hisse Senetleri İhraç Primleri''
WHEN	521	 THEN	''      02. Hisse Senedi İptal Karları''
WHEN	522	 THEN	''      03. M.D.V. Yeniden Değerleme Artışları''
WHEN	523	 THEN	''      04. İştirakler Yeniden Değerleme Artışları''
WHEN	529	 THEN	''      05. Diğer Sermaye Yedekleri''
WHEN	540	 THEN	''      01. Yasal Yedekler''
WHEN	541	 THEN	''      02. Statü Yedekleri''
WHEN	542	 THEN	''      03. Olağanüstü Yedekler''
WHEN	548	 THEN	''      04. Diğer Kar Yedekleri''
WHEN	549	 THEN	''      05. Özel Fonlar''
WHEN	570	 THEN	''    D GEÇMİŞ YILLAR KARLARI''
WHEN	580	 THEN	''    E GEÇMİŞ YILLAR ZARARLARI (-)''
WHEN	590	 THEN	''      01. Dönem Net Karı''
WHEN	591	 THEN	''      02. Dönem Net Zararı (-)''




ELSE ''DİĞER'' END Tip4, 
EMUHACC.code as [Hesap Kodu],EMUHACC.DEFINITION_ as [Hesap Adı],
ROUND(SUM(EMFLINE.DEBIT - EMFLINE.CREDIT),2) as [Değer]

from 


{DATABASE}LG_{FIRMA}_{DONEM}_EMFICHE EMFICHE,{DATABASE}LG_{FIRMA}_{DONEM}_EMFLINE EMFLINE,{DATABASE}LG_{FIRMA}_EMUHACC EMUHACC

WHERE

EMFICHE.LOGICALREF=EMFLINE.ACCFICHEREF  AND  EMFLINE.ACCOUNTREF=EMUHACC.LOGICALREF    AND SUBSTRING(EMFLINE.KEBIRCODE,1,1)<6

AND (EMFLINE.DATE_  BETWEEN @_BASTAR AND @_BITTAR)
GROUP BY  EMFLINE.KEBIRCODE,EMUHACC.code,EMUHACC.DEFINITION_ 


', 8001, 4000)
     SET @QUERY4 = SUBSTRING('select
CASE WHEN SUBSTRING(EMFLINE.KEBIRCODE,1,1)<3 THEN  ''Aktif Varlıklar''  ELSE ''Pasif Varlıklar'' END as Tip1, 
CASE WHEN SUBSTRING(EMFLINE.KEBIRCODE,1,1)=1 THEN  ''I.DÖNEN VARLIKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=2) THEN  ''II.DURAN VARLIKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=3) THEN  ''I.KISA VADELİ YABANCI KAYNAKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=4) THEN  ''II.UZUN VADELİ YABANCI KAYNAKLAR''  ELSE 
(CASE WHEN (SUBSTRING(EMFLINE.KEBIRCODE,1,1)=5) THEN  ''III.ÖZ KAYNAKLAR''  ELSE ''DİĞER'' END ) END ) END ) END ) END as Tip2, 
CASE  SUBSTRING(EMFLINE.KEBIRCODE,1,2) WHEN 10 THEN  ''A.HAZIR DEĞERLER''  
WHEN 11 THEN  ''B.MENKUL KIYMETLER''  
WHEN 12 THEN  ''C.TİCARİ ALACAKLAR''  
WHEN 13 THEN  ''D.DİĞER ALACAKLAR''  
WHEN 15 THEN  ''E.STOKLAR'' 
WHEN 17 THEN  ''F.YILLARA YAYGIN İNŞAAT VE ONARIM MALİYETLERİ'' 
WHEN 18 THEN  ''G.GELECEK AYLARA AİT GİDERLER VE GELİR TAHAKUKLARI'' 
WHEN 19 THEN  ''H.DİĞER DÖNEN VARLIKLAR'' 
WHEN 22 THEN  ''A.TİCARİ ALACAKLAR''
WHEN 23 THEN  ''B.DİĞER ALACAKLAR''
WHEN 24 THEN  ''C.MALİ DURAN VARLIKLAR''
WHEN 25 THEN  ''D.MADDİ DURAN VARLIKLAR''
WHEN 26 THEN  ''E.MADDİ OLMAYAN DURAN VARLIKLAR''
WHEN 27 THEN  ''F.ÖZEL TÜKENMEYE TABİ VARLIKLAR ''
WHEN 28 THEN  ''G.GELECEK YILLARA AİD GİDERLER VE GELİR TAHAKUKLARI''  
WHEN 29 THEN  ''H.DİĞER DURAN VARLIKLAR'' 
WHEN 30 THEN  ''A.MALİ BORÇLAR''
WHEN 32 THEN  ''B.TİCARİ BORÇLAR'' 
WHEN 33 THEN  ''C.DİĞER BORÇLAR'' 
WHEN 34 THEN  ''D.ALINAN AVANSLAR'' 
WHEN 35 THEN  ''E.YILLARA YAYGIN İNŞAAT VE ONARIM HAKEDİŞLERİ'' 
WHEN 36 THEN  ''F.ÖDENECEK VERGİ VE DİĞER HÜKÜMLÜKLER'' 
WHEN 37 THEN  ''G.BORÇ VE GİDER KARŞILIKLARI'' 
WHEN 38 THEN  ''H.GELECEK AYLARA AİD GELİRLER VE GİDER TAHAKUKLARI'' 
WHEN 39 THEN  ''J.DİĞER KISA VADELİ YABANCI KAYNAKLAR'' 
WHEN 40 THEN  ''A.MALİ BORÇLAR''
WHEN 42 THEN  ''B.TİCARİ BORÇLAR'' 
WHEN 43 THEN  ''C.DİĞER BORÇLAR'' 
WHEN 44 THEN  ''D.ALINAN AVANSLAR'' 
WHEN 47 THEN  ''E.BORÇ VE GİDER KARŞILIKLARI'' 
WHEN 48 THEN  ''F.GELECEK YILLARA AİD GELİRLER VE GİDER TAHAKUKLARI'' 
WHEN 49 THEN  ''G.DİĞER UZUN VADELİ YABANCI KAYNAKLAR'' 
WHEN 50 THEN  ''A.ÖDENMİŞ SERMAYE''
WHEN 52 THEN  ''B.SERMAYE YEDEKLERİ''
WHEN 54 THEN  ''C.KAR YEDEKLERİ''
WHEN 57 THEN  ''D.GEÇMİŞ YILLAR KARLARI''
WHEN 58 THEN  ''E.GEÇMİŞ YILLAR ZARARLARI''
WHEN 59 THEN  ''F.DÖNEM NET KARI (ZARARI)''
ELSE ''DİĞER'' END  as Tip3,
CASE  EMFLINE.KEBIRCODE 
WHEN	100	 THEN	''     01. Kasa''
WHEN	101	 THEN	''     02. Alınan Çekler''
WHEN	102	 THEN	''     03. Banka''
WHEN	103	 THEN	''     04. Verilen Çekler ve Ödeme Emirleri (-)''
WHEN	108	 THEN	''     05. Diğer Hazır Değerler''
WHEN	110	 THEN	''     01. Hisse Senetleri              ''
WHEN	111	 THEN	''     02. Özel Kesim Tahvil, Senet ve Bonoları''
WHEN	112	 THEN	''     03. Kamu Kesimi Tahvil, Senet ve Bonoları      ''
WHEN	118	 THEN	''     04. Diğer Menkul Kıymetler ''
WHEN	119	 THEN	''     05. Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)''
WHEN	120	 THEN	''     01. Alıcılar''
WHEN	121	 THEN	''     02. Alacak Senetleri''
WHEN	122	 THEN	''     03. Alacak Senetleri Reeskontu (-)''
WHEN	126	 THEN	''     04. Verilen Depozito ve Teminatlar''
WHEN	127	 THEN	''     05. Diğer Ticari Alacaklar''
WHEN	128	 THEN	''     06. Şüpheli Ticari Alacaklar''
WHEN	129	 THEN	''     07. Şüpheli Ticari Alacaklar Karşılığı (-)''
WHEN	131	 THEN	''     01. Ortaklardan Alacaklar''
WHEN	132	 THEN	''     02. İştiraklerden Alacaklar''
WHEN	133	 THEN	''     03. Bağlı Ortaklıklardan Alacaklar''
WHEN	135	 THEN	''     04. Personelden Alacaklar ''
WHEN	136	 THEN	''     05. Diğer Çeşitli Alacaklar''
WHEN	137	 THEN	''     06. Diğer Alacak Senetleri Reeskontu (-)''
WHEN	138	 THEN	''     07. Şüpheli Diğer Alacaklar''
WHEN	139	 THEN	''     08. Şüpheli Diğer Alacaklar Karşılığı (-)''
WHEN	150	 THEN	''     01. İlk Madde ve Malzeme''
WHEN	151	 THEN	''     02. Yarı Mamuller - Üretim''
WHEN	152	 THEN	''     03. Mamuller''
WHEN	153	 THEN	''     04. Ticari Mallar ''
WHEN	157	 THEN	''     05. Diğer Stoklar''
WHEN	158	 THEN	''     06. Stok Değer Düşüklüğü Karşılığı (-) ''
WHEN	159	 THEN	''     07. Verilen Sipariş Avansları''
WHEN	170	 THEN	''     01. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	171	 THEN	''     02. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	172	 THEN	''     03. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	173	 THEN	''     04. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	174	 THEN	''     05. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	175	 THEN	''     06. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	176	 THEN	''     07. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	177	 THEN	''     08. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	178	 THEN	''     09. Yıllara Yaygın İnşaat ve Onarım Maliyetleri''
WHEN	179	 THEN	''     10. Taşeronlara Verilen Avanslar''
WHEN	180	 THEN	''     01. Gelecek Aylara Ait Giderler''
WHEN	181	 THEN	''     02. Gelir Tahakkukları''
WHEN	190	 THEN	''     01. Devreden KDV''
WHEN	191	 THEN	''     02. İndirilecek Katma Değer Vergisi''
WHEN	192	 THEN	''     03. Diğer Katma Değer Vergisi''
WHEN	193	 THEN	''     04. Peşin Ödenen Vergiler ve Fonlar''
WHEN	195	 THEN	''     05. İş Avansları''
WHEN	196	 THEN	''     06.  Personel Avansları''
WHEN	197	 THEN	''     07. Sayım ve Tesellüm Noksanları''
WHEN	198	 THEN	''     08. Diğer Çeşitli Dönen Varlıklar''
WHEN	199	 THEN	''     09. Diğer Dönen Varlıklar Karşılığı (-)''
WHEN	220	 THEN	''     01. Alıcılar''
WHEN	221	 THEN	''     02. Alacak Senetleri''
WHEN	222	 THEN	''     03. Alacak Senetleri Reeskontu (-)''
WHEN	226	 THEN	''     04. Verilen Depozito ve Teminatlar''
WHEN	229	 THEN	''     05. Şüpheli Alacaklar Karşılığı (-)''
WHEN	231	 THEN	''     01. Ortaklardan Alacaklar''
WHEN	232	 THEN	''     02. İştiraklerden Alacaklar''
WHEN	233	 THEN	''     03. Bağlı Ortaklıklardan Alacaklar''
WHEN	235	 THEN	''     04. Personelden Alacaklar''
WHEN	236	 THEN	''     05. Diğer Çeşitli Alacaklar''
WHEN	237	 THEN	''     06. Diğer Alacak Senetleri Reeskontu (-)''
WHEN	239	 THEN	''     07. Şüpheli Diğer Alacaklar Karşılığı (-)''
WHEN	240	 THEN	''     01. Bağlı Menkul Kıymetler''
WHEN	241	 THEN	''     02. Bağlı Menkul Kıymetler Değer Düşüklüğü Karşılığı (-)''
WHEN	242	 THEN	''     03. İştirakler''
WHEN	243	 THEN	''     04. İştiraklere Sermaye Taahhütleri (-)''
WHEN	244	 THEN	''     05. İştirakler Sermaye Payları Değer Düşüklüğü Karşılığı (-)''
WHEN	245	 THEN	''     06. Bağlı Ortaklıklar''
WHEN	246	 THEN	''     07. Bağlı Ortaklıklara Sermaye Taahhütleri (-)''
WHEN	247	 THEN	''     08. Bağlı Ortaklıklar Sermaye Payları Değer Düşüklüğü Karşılığı (-)''
WHEN	248	 THEN	''     09. Diğer Mali Duran Varlıklar''
WHEN	249	 THEN	''     10. Diğer Mali Duran Varlıklar Değer Düşüklüğü Karşılığı (-)''
WHEN	250	 THEN	''     01. Arazi ve Arsalar''
WHEN	251	 THEN	''     02. Yer Altı ve Yer Üstü Düzenleri''
WHEN	252	 THEN	''     03. Binalar''
WHEN	253	 THEN	''     04. Tesis, Makine ve Cihazlar''
WHEN	254	 THEN	''     05. Taşıtlar''
WHEN	255	 THEN	''     06. Demirbaşlar''
WHEN	256	 THEN	''     07. Diğer Maddi Duran Varlıklar''
WHEN	257	 THEN	''     08. Birikmiş Amortismanlar (-)''
WHEN	258	 THEN	''     09. Yapılmakta Olan Yatırımlar''
WHEN	259	 THEN	''     10. Verilen Avanslar''
WHEN	260	 THEN	''     01. Haklar''
WHEN	261	 THEN	''     02. Şerefiye''
WHEN	262	 THEN	''     03. Kuruluş ve Örgütlenme Giderleri''
WHEN	263	 THEN	''     04. Araştırma ve Geliştirme Giderleri''
WHEN	264	 THEN	''     05. Özel Maliyetler''
WHEN	267	 THEN	''     06. Diğer Maddi Olmayan Duran Varlıklar''
WHEN	268	 THEN	''     07. Birikmiş Amortismanlar (-)''
WHEN	269	 THEN	''     08. Verilen Avanslar''
WHEN	271	 THEN	''     01. Arama Giderleri''
WHEN	272	 THEN	''     02. Hazırlık ve Geliştirme Giderleri''
WHEN	277	 THEN	''     03. Diğer Özel Tükenmeye Tabi Varlıklar''
WHEN	278	 THEN	''     04. Birikmiş Tükenme Payları (-)''
WHEN	279	 THEN	''     05. Verilen Avanslar''
WHEN	280	 THEN	''     01. Gelecek Yıllara Ait Giderler''
WHEN	281	 THEN	''     02. Gelir Tahakkukları''
WHEN	291	 THEN	''     01. Gelecek Yıllarda İndirilecek Katma Değer Vergisi''
WHEN	292	 THEN	''     02. Diğer Katma Değer Vergisi''
WHEN	295	 THEN	''     03. Peşin Ödenen Vergiler ve Fonlar''
WHEN	297	 THEN	''     04. Diğer Çeşitli Duran Varlıklar''
WHEN	300	 THEN	''      01. Banka Kredileri''
WHEN	303	 THEN	''      02. Uzun Vadeli Kredilerin Anapara Taksitleri ve Faizleri''
WHEN	304	 THEN	''      03. Tahvil Anapara Borç, Taksit ve Faizleri''
WHEN	305	 THEN	''      04. Çıkarılmış Bonolar ve Senetler''
WHEN	306	 THEN	''      05. Çıkarılmış Diğer Menkul Kıymetler''
WHEN	308	 THEN	''      06. Menkul Kıymetler İhraç Farkı (-)''
WHEN	309	 THEN	''      07. Diğer Mali Borçlar''
WHEN	320	 THEN	''      01. Satıcılar''
WHEN	321	 THEN	''      02. Borç Senetleri''
WHEN	322	 THEN	''      03. Borç Senetleri Reeskontu (-)''
WHEN	326	 THEN	''      04. Alınan Depozito ve Teminatlar''
WHEN	329	 THEN	''      05. Diğer Ticari Borçlar''
WHEN	331	 THEN	''      01. Ortaklara Borçlar''
WHEN	332	 THEN	''      02. İştiraklere Borçlar''
WHEN	333	 THEN	''      03. Bağlı Ortaklıklara Borçlar''
WHEN	335	 THEN	''      04. Personele Borçlar''
WHEN	336	 THEN	''      05. Diğer Çeşitli Borçlar''
WHEN	337	 THEN	''      06. Diğer Borç Senetleri Reeskontu (-)''
WHEN	340	 THEN	''      01. Alınan Sipariş Avansları''
WHEN	349	 THEN	''      02. Alınan Diğer Avanslar''
WHEN	350	 THEN	''      01. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	351	 THEN	''      02. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	352	 THEN	''      03. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	353	 THEN	''      04. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	354	 THEN	''      05. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	355	 THEN	''      06. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	356	 THEN	''      07. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	357	 THEN	''      08. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	358	 THEN	''      09. Yıllara Yaygın İnşaat ve Onarım Hakediş Bedelleri''
WHEN	360	 THEN	''      01. Ödenecek Vegi ve Fonlar''
WHEN	361	 THEN	''      02. Ödenecek Sosyal Güvenlik Kesintileri''
WHEN	368	 THEN	''      03. Vadesi Geçmiş Ertelenmiş Veya Taksitlendirilmiş Vergi ve Diğer Yüküml.''
WHEN	369	 THEN	''      04. Ödenecek Diğer Yükümlülükler''
WHEN	370	 THEN	''      01. Dönem Karı Vergi ve Diğer Yasal Yükümlülük Karşılıkları''
WHEN	371	 THEN	''      02. Dönem Karının Peşin Ödenen Vergi ve Diğer Yükümlülükleri (-)''
WHEN	372	 THEN	''      03. Kıdem Tazminatı Karşılığı''
WHEN	373	 THEN	''      04. Maliyet Giderleri Karşılığı''
WHEN	379	 THEN	''      05. Diğer Borç ve Gider Karşılıkları''
WHEN	380	 THEN	''      01. Gelecek Aylara Ait Gelirler''
WHEN	381	 THEN	''      02. Gider Tahakkukları''
WHEN	391	 THEN	''      01. Hesaplanan KDV''
WHEN	392	 THEN	''      02. Diğer KDV''
WHEN	393	 THEN	''      03. Merkez ve Şubeler Cari Hesabı''
WHEN	397	 THEN	''      04. Sayım ve Tesellüm Fazlaları''
WHEN	399	 THEN	''      05. Diğer Çeşitli Yabancı Kaynaklar''
WHEN	400	 THEN	''      01. Banka Kredileri''
WHEN	405	 THEN	''      02. Çıkarılmış Tahviller''
WHEN	407	 THEN	''      03. Çıkarılmış Diğer Menkul Kıymetler''
WHEN	408	 THEN	''      04. Menkul Kıymetler İhraç Farkı (-)''
WHEN	409	 THEN	''      05. Diğer Mali Borçlar''
WHEN	420	 THEN	''      01. Satıcılar''
WHEN	421	 THEN	''      02. Borç Senetleri''
WHEN	422	 THEN	''      03. Borç Senetleri Reeskontu (-)''
WHEN	426	 THEN	''      04. Alınan Depozito ve Teminatlar''
WHEN	429	 THEN	''      05. Diğer Ticari Borçlar''
WHEN	431	 THEN	''      01. Ortaklara Borçlar''
WHEN	432	 THEN	''      02. İştiraklere Borçlar''
WHEN	433	 THEN	''      03. Bağlı Ortaklıklara Borçlar''
WHEN	436	 THEN	''      04. Diğer Çeşitli Borçlar''
WHEN	437	 THEN	''      05. Diğer Borç Senetleri Reeskontu (-)''
WHEN	438	 THEN	''      06. Kamuya Olan Ertelenmiş Veya Taksitlendirilmiş Borçlar''
WHEN	472	 THEN	''      01. Kıdem Tazminatı Karşılığı''
WHEN	479	 THEN	''      02. Diğer Borç ve Gider Karşılıkları''
WHEN	480	 THEN	''      01. Gelecek Yıllara Ait Gelirler''
WHEN	481	 THEN	''      02. Gider Tahakkukları''
WHEN	492	 THEN	''      01. Gelecek Yıllara Ertelenen Veya Terkin Edilen Katma Değer Vergisi''
WHEN	493	 THEN	''      02. Tesise Katılma Payları''
WHEN	499	 THEN	''      03. Diğer Çeşitli Uzun Vadeli Yabancı Kaynaklar''
WHEN	500	 THEN	''      01. Sermaye''
WHEN	501	 THEN	''      02. Ödenmemiş Sermaye (-)''
WHEN	520	 THEN	''      01. Hisse Senetleri İhraç Primleri''
WHEN	521	 THEN	''      02. Hisse Senedi İptal Karları''
WHEN	522	 THEN	''      03. M.D.V. Yeniden Değerleme Artışları''
WHEN	523	 THEN	''      04. İştirakler Yeniden Değerleme Artışları''
WHEN	529	 THEN	''      05. Diğer Sermaye Yedekleri''
WHEN	540	 THEN	''      01. Yasal Yedekler''
WHEN	541	 THEN	''      02. Statü Yedekleri''
WHEN	542	 THEN	''      03. Olağanüstü Yedekler''
WHEN	548	 THEN	''      04. Diğer Kar Yedekleri''
WHEN	549	 THEN	''      05. Özel Fonlar''
WHEN	570	 THEN	''    D GEÇMİŞ YILLAR KARLARI''
WHEN	580	 THEN	''    E GEÇMİŞ YILLAR ZARARLARI (-)''
WHEN	590	 THEN	''      01. Dönem Net Karı''
WHEN	591	 THEN	''      02. Dönem Net Zararı (-)''




ELSE ''DİĞER'' END Tip4, 
EMUHACC.code as [Hesap Kodu],EMUHACC.DEFINITION_ as [Hesap Adı],
ROUND(SUM(EMFLINE.DEBIT - EMFLINE.CREDIT),2) as [Değer]

from 


{DATABASE}LG_{FIRMA}_{DONEM}_EMFICHE EMFICHE,{DATABASE}LG_{FIRMA}_{DONEM}_EMFLINE EMFLINE,{DATABASE}LG_{FIRMA}_EMUHACC EMUHACC

WHERE

EMFICHE.LOGICALREF=EMFLINE.ACCFICHEREF  AND  EMFLINE.ACCOUNTREF=EMUHACC.LOGICALREF    AND SUBSTRING(EMFLINE.KEBIRCODE,1,1)<6

AND (EMFLINE.DATE_  BETWEEN @_BASTAR AND @_BITTAR)
GROUP BY  EMFLINE.KEBIRCODE,EMUHACC.code,EMUHACC.DEFINITION_ 


', 12001, 4000)

      SET @QUERY = @QUERY1 + @QUERY2 + @QUERY3 + @QUERY4 + @QUERY5 + @QUERY6 + @QUERY7 + @QUERY8 + @QUERY9 + @QUERY10 + @QUERY11 + @QUERY12 + @QUERY13 + @QUERY14 + @QUERY15 + @QUERY16 + @QUERY17 + @QUERY18 + @QUERY19 + @QUERY20
      SET @QUERY = REPLACE(REPLACE(REPLACE(@QUERY, '{DATABASE}',@DB), '{FIRMA}',@FIRM), '{DONEM}', @DONEM)

     EXECUTE sp_executesql @QUERY, @PARAMETRELER, @_BASTAR = @_BASTAR_VALUE, @_BITTAR = @_BITTAR_VALUE;
END
GO
