USE TIGER_FERCAM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE DP_RAPOR_KASA_EKSTRE @DB NVARCHAR(50), @FIRM NVARCHAR(3), @DONEM NVARCHAR(2) ,
                                      @_BASTAR_VALUE DATETIME,
                                      @_BITTAR_VALUE DATETIME,
                                      @_KODU_VALUE NVARCHAR(50)
 
AS
BEGIN
     DECLARE @QUERY NVARCHAR(MAX)
     DECLARE @QUERY1 NVARCHAR(MAX)
     DECLARE @QUERY2 NVARCHAR(MAX)
     DECLARE @QUERY3 NVARCHAR(MAX)
     DECLARE @QUERY4 NVARCHAR(MAX)
     DECLARE @QUERY5 NVARCHAR(MAX)
     DECLARE @QUERY6 NVARCHAR(MAX)
     DECLARE @QUERY7 NVARCHAR(MAX)
     DECLARE @QUERY8 NVARCHAR(MAX)
     DECLARE @QUERY9 NVARCHAR(MAX)
     DECLARE @QUERY10 NVARCHAR(MAX)
     DECLARE @QUERY11 NVARCHAR(MAX)
     DECLARE @QUERY12 NVARCHAR(MAX)
     DECLARE @QUERY13 NVARCHAR(MAX)
     DECLARE @QUERY14 NVARCHAR(MAX)
     DECLARE @QUERY15 NVARCHAR(MAX)
     DECLARE @QUERY16 NVARCHAR(MAX)
     DECLARE @QUERY17 NVARCHAR(MAX)
     DECLARE @QUERY18 NVARCHAR(MAX)
     DECLARE @QUERY19 NVARCHAR(MAX)
     DECLARE @QUERY20 NVARCHAR(MAX)

     DECLARE @PARAMETRELER NVARCHAR(MAX)

     SET @PARAMETRELER = N'@_BASTAR DATETIME,@_BITTAR DATETIME,@_KODU NVARCHAR(50)';

     SET @QUERY1 = ''
     SET @QUERY2 = ''
     SET @QUERY3 = ''
     SET @QUERY4 = ''
     SET @QUERY5 = ''
     SET @QUERY6 = ''
     SET @QUERY7 = ''
     SET @QUERY8 = ''
     SET @QUERY9 = ''
     SET @QUERY10 = ''
     SET @QUERY11 = ''
     SET @QUERY12 = ''
     SET @QUERY13 = ''
     SET @QUERY14 = ''
     SET @QUERY15 = ''
     SET @QUERY16 = ''
     SET @QUERY17 = ''
     SET @QUERY18 = ''
     SET @QUERY19 = ''
     SET @QUERY20 = ''

     SET @QUERY1 = SUBSTRING('SELECT 
CASE KSL.TRCODE WHEN 11 THEN ''Tahsilat'' WHEN 12 THEN ''Ödeme'' WHEN 21 THEN ''Bankaya Yatırılan'' WHEN 22 THEN ''Bankadan Çekilen'' 
WHEN 31 THEN ''Peşin Alım'' WHEN 32 THEN ''Peşin Satış İade''  WHEN 33 THEN ''Peşin Satış İade'' WHEN 34 THEN ''Peşin Alım''  WHEN 35 THEN ''Peşin Alım İade'' 
WHEN 36 THEN ''Peşin Satış'' WHEN 37 THEN ''Peşin Satış'' WHEN 38 THEN ''Peşin Satış'' WHEN 41 THEN ''Muhasebe Tahsil'' WHEN 42 THEN ''Muhasebe Tediye''  
WHEN 61 THEN ''Çek Tahsili'' WHEN 62 THEN ''Senet Tahsili''  WHEN 63 THEN ''Çek Ödemesi'' WHEN 64 THEN ''Senet Ödemesi'' WHEN 71 THEN ''Açılış Borç'' WHEN 72 THEN ''Açılış Alacak'' 
WHEN 73 THEN ''Virman Borç'' WHEN 74 THEN ''Virman Alacak'' WHEN 75 THEN ''Gider Pusulası'' WHEN 76 THEN ''Verilen Serbest Meslek Makbuzu'' WHEN 77 THEN ''Alınan Serbest Meslek Makbuzu'' 
WHEN 79 THEN ''Kur Farkı Borç'' WHEN 80 THEN ''Kur Farkı Alacak'' else ''Diğer'' end Tür,ksc.code as ''Kasa Kodu'',ksc.NAME as ''Kasa Adı'',ksl.date_ as ''Tarih'',
case KSL.SIGN WHEN 0 THEN AMOUNT ELSE 0 END  ''Tahsilat'',case KSL.SIGN WHEN 1 THEN AMOUNT ELSE 0 END  ''Ödeme''  
FROM {DATABASE}LG_{FIRMA}_{DONEM}_KSLINES KSL,{DATABASE}LG_{FIRMA}_KSCARD KSC
WHERE KSL.CARDREF=KSC.LOGICALREF and ksl.CANCELLED=0
and (@_KODU='''' OR KSC.CODE LIKE REPLACE(@_KODU,''*'',''%'')) AND (KSL.DATE_ BETWEEN @_BASTAR AND @_BITTAR)
', 1, 4000)

      SET @QUERY = @QUERY1 + @QUERY2 + @QUERY3 + @QUERY4 + @QUERY5 + @QUERY6 + @QUERY7 + @QUERY8 + @QUERY9 + @QUERY10 + @QUERY11 + @QUERY12 + @QUERY13 + @QUERY14 + @QUERY15 + @QUERY16 + @QUERY17 + @QUERY18 + @QUERY19 + @QUERY20
      SET @QUERY = REPLACE(REPLACE(REPLACE(@QUERY, '{DATABASE}',@DB), '{FIRMA}',@FIRM), '{DONEM}', @DONEM)

     EXECUTE sp_executesql @QUERY, @PARAMETRELER, @_BASTAR = @_BASTAR_VALUE, @_BITTAR = @_BITTAR_VALUE, @_KODU = @_KODU_VALUE;
END
GO
