USE TIGER_FERCAM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE DP_RAPOR_NAKIT_AKIS @DB NVARCHAR(50), @FIRM NVARCHAR(3), @DONEM NVARCHAR(2)  
AS
BEGIN
     DECLARE @QUERY NVARCHAR(MAX)
     DECLARE @QUERY1 NVARCHAR(MAX)
     DECLARE @QUERY2 NVARCHAR(MAX)
     DECLARE @QUERY3 NVARCHAR(MAX)
     DECLARE @QUERY4 NVARCHAR(MAX)
     DECLARE @QUERY5 NVARCHAR(MAX)
     DECLARE @QUERY6 NVARCHAR(MAX)
     DECLARE @QUERY7 NVARCHAR(MAX)
     DECLARE @QUERY8 NVARCHAR(MAX)
     DECLARE @QUERY9 NVARCHAR(MAX)
     DECLARE @QUERY10 NVARCHAR(MAX)
     DECLARE @QUERY11 NVARCHAR(MAX)
     DECLARE @QUERY12 NVARCHAR(MAX)
     DECLARE @QUERY13 NVARCHAR(MAX)
     DECLARE @QUERY14 NVARCHAR(MAX)
     DECLARE @QUERY15 NVARCHAR(MAX)
     DECLARE @QUERY16 NVARCHAR(MAX)
     DECLARE @QUERY17 NVARCHAR(MAX)
     DECLARE @QUERY18 NVARCHAR(MAX)
     DECLARE @QUERY19 NVARCHAR(MAX)
     DECLARE @QUERY20 NVARCHAR(MAX)


     SET @QUERY1 = ''
     SET @QUERY2 = ''
     SET @QUERY3 = ''
     SET @QUERY4 = ''
     SET @QUERY5 = ''
     SET @QUERY6 = ''
     SET @QUERY7 = ''
     SET @QUERY8 = ''
     SET @QUERY9 = ''
     SET @QUERY10 = ''
     SET @QUERY11 = ''
     SET @QUERY12 = ''
     SET @QUERY13 = ''
     SET @QUERY14 = ''
     SET @QUERY15 = ''
     SET @QUERY16 = ''
     SET @QUERY17 = ''
     SET @QUERY18 = ''
     SET @QUERY19 = ''
     SET @QUERY20 = ''

     SET @QUERY1 = SUBSTRING('SELECT     ''Tahsilat'' AS Tür, ''Fatura'' AS Bölüm, CLCARD.CODE AS [Kodu], CLCARD.DEFINITION_ AS [Ünvanı], CLCARD.SPECODE AS [Özel Kod],
                      PAYTRANS.DATE_ AS Vade, MONTH(PAYTRANS.DATE_) AS [Vade Ay], YEAR(PAYTRANS.DATE_) AS [Vade Yıl], 
                      case PAYTRANS.TRCURR WHEN 0 THEN (PAYTRANS.TOTAL - PAYTRANS.PAID) ELSE (PAYTRANS.TOTAL - PAYTRANS.PAID)*PAYTRANS.TRRATE END AS Tutar,
					  case PAYTRANS.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS.TRCURR) end AS Döviz,
					   (PAYTRANS.TOTAL - PAYTRANS.PAID)  AS [Dövizli Tutar]					  
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS  PAYTRANS INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD  CLCARD ON PAYTRANS.CARDREF = CLCARD.LOGICALREF
WHERE     (PAYTRANS.SIGN = 0) AND (PAYTRANS.MODULENR = ''4'') AND 
                      (PAYTRANS.TOTAL - PAYTRANS.PAID > 0) AND PAYTRANS.PAIDINCASH=0
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Fatura'' AS Bölüm, CLCARD.CODE AS [Kodu], CLCARD.DEFINITION_ AS [Ünvanı], CLCARD.SPECODE AS [Özel Kod],
                      PAYTRANS.DATE_ AS Vade, MONTH(PAYTRANS.DATE_) AS [Vade Ay], YEAR(PAYTRANS.DATE_) AS [Vade Yıl], 
                      case PAYTRANS.TRCURR WHEN 0 THEN (PAYTRANS.TOTAL - PAYTRANS.PAID)*-1 ELSE (PAYTRANS.TOTAL - PAYTRANS.PAID)*PAYTRANS.TRRATE*-1 END AS Tutar,
					  case PAYTRANS.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS.TRCURR) end AS Döviz,
					   (PAYTRANS.TOTAL - PAYTRANS.PAID)*-1  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS  PAYTRANS INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD  CLCARD ON PAYTRANS.CARDREF = CLCARD.LOGICALREF
WHERE     (PAYTRANS.SIGN = 1) AND (PAYTRANS.MODULENR = ''4'') AND 
                      (PAYTRANS.TOTAL - PAYTRANS.PAID > 0) AND PAYTRANS.PAIDINCASH=0
UNION ALL
SELECT ''Tahsilat'' AS Tür, CASE DOC WHEN 1 THEN ''Çek'' else ''Senet'' end AS Bölüm,
	(SELECT TOP 1 CLCARD.code  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Kodu],
	(SELECT TOP 1 CLCARD.DEFINITION_  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Ünvanı], 
		(SELECT TOP 1 CLCARD.SPECODE  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Özel Kod],
		DUEDATE AS [Vade],
		MONTH(DUEDATE)  AS [Vade Ay],
		YEAR (DUEDATE) AS [Vade Yıl],		
	amount AS [Tutar],
	CASE WHEN TRCURR = 0 THEN ''TL'' 
		 ELSE (Select CURCODE  FROM L_CURRENCYLIST WHERE CURTYPE = CSCARD.TRCURR AND FIRMNR = 001) END AS Döviz,
		 TRNET AS [Dövizli Tutar]
FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSCARD CSCARD 
WHERE  DOC IN (1,2) AND CURRSTAT IN (1,3,4,5)
	  
UNION ALL
SELECT ''Ödeme'' AS Tür, CASE DOC WHEN 3 THEN ''Çek'' else ''Senet'' end AS Bölüm,
	(SELECT TOP 1 CLCARD.code  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Kodu],
	(SELECT TOP 1 CLCARD.DEFINITION_  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Ünvanı], 
		(SELECT TOP 1 CLCARD.SPECODE  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Özel Kod],
		DUEDATE AS [Vade],
		MONTH(DUEDATE)  AS [Vade Ay],
		YEAR (DUEDATE) AS [Vade Yıl],		
	amount*-1 AS [Tutar],
	CASE WHEN TRCURR = 0 THEN ''TL'' 
		 ELSE (Select CURCODE  FROM L_CURRENCYLIST WHERE CURTYPE = CSCARD.TRCURR AND FIRMNR = 001) END AS Döviz,
		 TRNET*-1 AS [Dövizli Tutar]
FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSCARD CSCARD 
WHERE  DOC IN (3,4) AND CURRSTAT IN (9,10)


	  
UNION ALL
SELECT     ''Tahsilat'' AS Tür, ''Kredi Kartı'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı], CLCARD_2.SPECODE AS [Özel Kod], 
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl], case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL ) ELSE (PAYTRANS_2.TOTAL)*PAYTRANS_2.TRRATE END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 1) AND (PAYTRANS_2.MODULENR = ''5'') AND (PAYTRANS_2.TRCODE = ''70'')
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Kredi Kartı'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı], CLCARD_2.SPECODE AS [Özel Kod],
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl], case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL *-1) ELSE (PAYTRANS_2.TOTAL*-1)*PAYTRANS_2.TRRATE END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL*-1)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 0) AND (PAYTRANS_2.MODULENR = ''5'') AND (PAYTRANS_2.TRCODE = ''72'')
UNION ALL
SELECT     ''Tahsilat'' AS Tür, ''Açılış Fişi'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı],  CLCARD_2.SPECODE AS [Özel Kod],
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl],case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL ) ELSE (PAYTRANS_2.TOTAL)*PAYTRANS_2.TRRATE END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 0) AND (PAYTRANS_2.MODULENR = ''5'') AND 
                      (PAYTRANS_2.TOTAL - PAYTRANS_2.PAID > 0) AND (PAYTRANS_2.TRCODE = ''14'')
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Açılış Fişi'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı],  CLCARD_2.SPECODE AS [Özel Kod],
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl], case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL *-1) ELSE (PAYTRANS_2.TOTAL)*PAYTRANS_2.TRRATE *-1 END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 1) AND (PAYTRANS_2.MODULENR = ''5'') AND 
                      (PAYTRANS_2.TOTAL - PAYTRANS_2.PAID > 0) AND (PAYTRANS_2.TRCODE = ''14'')
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Banka Kredisi'' AS Bölüm, BANKACC.CODE AS Kodu, BANKACC.DEFINITION_ AS Ünvanı,  BANKACC.SPECODE AS [Özel Kod], 

                      BNCREPAYTR.DUEDATE AS Vade, MONTH(BNCREPAYTR.DUEDATE) AS [Vade Ay], YEAR(BNCREPAYTR.DUEDATE) 
                      AS [Vade Yıl], CASE WHEN BNCREPAYTR.TRANSTYPE=0 THEN (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL )* - 1  ELSE 
                      (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL ) END AS Tutar,''TL'' AS Döviz,CASE WHEN BNCREPAYTR.TRANSTYPE=0 THEN (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL )* - 1  ELSE 
                      (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL ) END AS [Dövizli Tutar]

FROM         {DATABASE}LG_{FIRMA}_BNCREPAYTR AS BNCREPAYTR INNER JOIN
                      {DATABASE}LG_{FIRMA}_BNCREDITCARD AS BNCREDITCARD ON BNCREPAYTR.CREDITREF = BNCREDITCARD.LOGICALREF INNER JOIN
                      {DATABASE}LG_{FIRMA}_BANKACC  AS BANKACC ON BNCREDITCARD.BNCRACCREF = BANKACC.LOGICALREF
                      

', 1, 4000)
     SET @QUERY2 = SUBSTRING('SELECT     ''Tahsilat'' AS Tür, ''Fatura'' AS Bölüm, CLCARD.CODE AS [Kodu], CLCARD.DEFINITION_ AS [Ünvanı], CLCARD.SPECODE AS [Özel Kod],
                      PAYTRANS.DATE_ AS Vade, MONTH(PAYTRANS.DATE_) AS [Vade Ay], YEAR(PAYTRANS.DATE_) AS [Vade Yıl], 
                      case PAYTRANS.TRCURR WHEN 0 THEN (PAYTRANS.TOTAL - PAYTRANS.PAID) ELSE (PAYTRANS.TOTAL - PAYTRANS.PAID)*PAYTRANS.TRRATE END AS Tutar,
					  case PAYTRANS.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS.TRCURR) end AS Döviz,
					   (PAYTRANS.TOTAL - PAYTRANS.PAID)  AS [Dövizli Tutar]					  
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS  PAYTRANS INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD  CLCARD ON PAYTRANS.CARDREF = CLCARD.LOGICALREF
WHERE     (PAYTRANS.SIGN = 0) AND (PAYTRANS.MODULENR = ''4'') AND 
                      (PAYTRANS.TOTAL - PAYTRANS.PAID > 0) AND PAYTRANS.PAIDINCASH=0
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Fatura'' AS Bölüm, CLCARD.CODE AS [Kodu], CLCARD.DEFINITION_ AS [Ünvanı], CLCARD.SPECODE AS [Özel Kod],
                      PAYTRANS.DATE_ AS Vade, MONTH(PAYTRANS.DATE_) AS [Vade Ay], YEAR(PAYTRANS.DATE_) AS [Vade Yıl], 
                      case PAYTRANS.TRCURR WHEN 0 THEN (PAYTRANS.TOTAL - PAYTRANS.PAID)*-1 ELSE (PAYTRANS.TOTAL - PAYTRANS.PAID)*PAYTRANS.TRRATE*-1 END AS Tutar,
					  case PAYTRANS.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS.TRCURR) end AS Döviz,
					   (PAYTRANS.TOTAL - PAYTRANS.PAID)*-1  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS  PAYTRANS INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD  CLCARD ON PAYTRANS.CARDREF = CLCARD.LOGICALREF
WHERE     (PAYTRANS.SIGN = 1) AND (PAYTRANS.MODULENR = ''4'') AND 
                      (PAYTRANS.TOTAL - PAYTRANS.PAID > 0) AND PAYTRANS.PAIDINCASH=0
UNION ALL
SELECT ''Tahsilat'' AS Tür, CASE DOC WHEN 1 THEN ''Çek'' else ''Senet'' end AS Bölüm,
	(SELECT TOP 1 CLCARD.code  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Kodu],
	(SELECT TOP 1 CLCARD.DEFINITION_  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Ünvanı], 
		(SELECT TOP 1 CLCARD.SPECODE  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Özel Kod],
		DUEDATE AS [Vade],
		MONTH(DUEDATE)  AS [Vade Ay],
		YEAR (DUEDATE) AS [Vade Yıl],		
	amount AS [Tutar],
	CASE WHEN TRCURR = 0 THEN ''TL'' 
		 ELSE (Select CURCODE  FROM L_CURRENCYLIST WHERE CURTYPE = CSCARD.TRCURR AND FIRMNR = 001) END AS Döviz,
		 TRNET AS [Dövizli Tutar]
FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSCARD CSCARD 
WHERE  DOC IN (1,2) AND CURRSTAT IN (1,3,4,5)
	  
UNION ALL
SELECT ''Ödeme'' AS Tür, CASE DOC WHEN 3 THEN ''Çek'' else ''Senet'' end AS Bölüm,
	(SELECT TOP 1 CLCARD.code  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Kodu],
	(SELECT TOP 1 CLCARD.DEFINITION_  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Ünvanı], 
		(SELECT TOP 1 CLCARD.SPECODE  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Özel Kod],
		DUEDATE AS [Vade],
		MONTH(DUEDATE)  AS [Vade Ay],
		YEAR (DUEDATE) AS [Vade Yıl],		
	amount*-1 AS [Tutar],
	CASE WHEN TRCURR = 0 THEN ''TL'' 
		 ELSE (Select CURCODE  FROM L_CURRENCYLIST WHERE CURTYPE = CSCARD.TRCURR AND FIRMNR = 001) END AS Döviz,
		 TRNET*-1 AS [Dövizli Tutar]
FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSCARD CSCARD 
WHERE  DOC IN (3,4) AND CURRSTAT IN (9,10)


	  
UNION ALL
SELECT     ''Tahsilat'' AS Tür, ''Kredi Kartı'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı], CLCARD_2.SPECODE AS [Özel Kod], 
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl], case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL ) ELSE (PAYTRANS_2.TOTAL)*PAYTRANS_2.TRRATE END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 1) AND (PAYTRANS_2.MODULENR = ''5'') AND (PAYTRANS_2.TRCODE = ''70'')
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Kredi Kartı'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı], CLCARD_2.SPECODE AS [Özel Kod],
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl], case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL *-1) ELSE (PAYTRANS_2.TOTAL*-1)*PAYTRANS_2.TRRATE END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL*-1)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 0) AND (PAYTRANS_2.MODULENR = ''5'') AND (PAYTRANS_2.TRCODE = ''72'')
UNION ALL
SELECT     ''Tahsilat'' AS Tür, ''Açılış Fişi'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı],  CLCARD_2.SPECODE AS [Özel Kod],
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl],case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL ) ELSE (PAYTRANS_2.TOTAL)*PAYTRANS_2.TRRATE END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 0) AND (PAYTRANS_2.MODULENR = ''5'') AND 
                      (PAYTRANS_2.TOTAL - PAYTRANS_2.PAID > 0) AND (PAYTRANS_2.TRCODE = ''14'')
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Açılış Fişi'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı],  CLCARD_2.SPECODE AS [Özel Kod],
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl], case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL *-1) ELSE (PAYTRANS_2.TOTAL)*PAYTRANS_2.TRRATE *-1 END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 1) AND (PAYTRANS_2.MODULENR = ''5'') AND 
                      (PAYTRANS_2.TOTAL - PAYTRANS_2.PAID > 0) AND (PAYTRANS_2.TRCODE = ''14'')
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Banka Kredisi'' AS Bölüm, BANKACC.CODE AS Kodu, BANKACC.DEFINITION_ AS Ünvanı,  BANKACC.SPECODE AS [Özel Kod], 

                      BNCREPAYTR.DUEDATE AS Vade, MONTH(BNCREPAYTR.DUEDATE) AS [Vade Ay], YEAR(BNCREPAYTR.DUEDATE) 
                      AS [Vade Yıl], CASE WHEN BNCREPAYTR.TRANSTYPE=0 THEN (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL )* - 1  ELSE 
                      (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL ) END AS Tutar,''TL'' AS Döviz,CASE WHEN BNCREPAYTR.TRANSTYPE=0 THEN (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL )* - 1  ELSE 
                      (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL ) END AS [Dövizli Tutar]

FROM         {DATABASE}LG_{FIRMA}_BNCREPAYTR AS BNCREPAYTR INNER JOIN
                      {DATABASE}LG_{FIRMA}_BNCREDITCARD AS BNCREDITCARD ON BNCREPAYTR.CREDITREF = BNCREDITCARD.LOGICALREF INNER JOIN
                      {DATABASE}LG_{FIRMA}_BANKACC  AS BANKACC ON BNCREDITCARD.BNCRACCREF = BANKACC.LOGICALREF
                      

', 4001, 4000)
     SET @QUERY3 = SUBSTRING('SELECT     ''Tahsilat'' AS Tür, ''Fatura'' AS Bölüm, CLCARD.CODE AS [Kodu], CLCARD.DEFINITION_ AS [Ünvanı], CLCARD.SPECODE AS [Özel Kod],
                      PAYTRANS.DATE_ AS Vade, MONTH(PAYTRANS.DATE_) AS [Vade Ay], YEAR(PAYTRANS.DATE_) AS [Vade Yıl], 
                      case PAYTRANS.TRCURR WHEN 0 THEN (PAYTRANS.TOTAL - PAYTRANS.PAID) ELSE (PAYTRANS.TOTAL - PAYTRANS.PAID)*PAYTRANS.TRRATE END AS Tutar,
					  case PAYTRANS.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS.TRCURR) end AS Döviz,
					   (PAYTRANS.TOTAL - PAYTRANS.PAID)  AS [Dövizli Tutar]					  
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS  PAYTRANS INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD  CLCARD ON PAYTRANS.CARDREF = CLCARD.LOGICALREF
WHERE     (PAYTRANS.SIGN = 0) AND (PAYTRANS.MODULENR = ''4'') AND 
                      (PAYTRANS.TOTAL - PAYTRANS.PAID > 0) AND PAYTRANS.PAIDINCASH=0
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Fatura'' AS Bölüm, CLCARD.CODE AS [Kodu], CLCARD.DEFINITION_ AS [Ünvanı], CLCARD.SPECODE AS [Özel Kod],
                      PAYTRANS.DATE_ AS Vade, MONTH(PAYTRANS.DATE_) AS [Vade Ay], YEAR(PAYTRANS.DATE_) AS [Vade Yıl], 
                      case PAYTRANS.TRCURR WHEN 0 THEN (PAYTRANS.TOTAL - PAYTRANS.PAID)*-1 ELSE (PAYTRANS.TOTAL - PAYTRANS.PAID)*PAYTRANS.TRRATE*-1 END AS Tutar,
					  case PAYTRANS.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS.TRCURR) end AS Döviz,
					   (PAYTRANS.TOTAL - PAYTRANS.PAID)*-1  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS  PAYTRANS INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD  CLCARD ON PAYTRANS.CARDREF = CLCARD.LOGICALREF
WHERE     (PAYTRANS.SIGN = 1) AND (PAYTRANS.MODULENR = ''4'') AND 
                      (PAYTRANS.TOTAL - PAYTRANS.PAID > 0) AND PAYTRANS.PAIDINCASH=0
UNION ALL
SELECT ''Tahsilat'' AS Tür, CASE DOC WHEN 1 THEN ''Çek'' else ''Senet'' end AS Bölüm,
	(SELECT TOP 1 CLCARD.code  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Kodu],
	(SELECT TOP 1 CLCARD.DEFINITION_  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Ünvanı], 
		(SELECT TOP 1 CLCARD.SPECODE  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Özel Kod],
		DUEDATE AS [Vade],
		MONTH(DUEDATE)  AS [Vade Ay],
		YEAR (DUEDATE) AS [Vade Yıl],		
	amount AS [Tutar],
	CASE WHEN TRCURR = 0 THEN ''TL'' 
		 ELSE (Select CURCODE  FROM L_CURRENCYLIST WHERE CURTYPE = CSCARD.TRCURR AND FIRMNR = 001) END AS Döviz,
		 TRNET AS [Dövizli Tutar]
FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSCARD CSCARD 
WHERE  DOC IN (1,2) AND CURRSTAT IN (1,3,4,5)
	  
UNION ALL
SELECT ''Ödeme'' AS Tür, CASE DOC WHEN 3 THEN ''Çek'' else ''Senet'' end AS Bölüm,
	(SELECT TOP 1 CLCARD.code  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Kodu],
	(SELECT TOP 1 CLCARD.DEFINITION_  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Ünvanı], 
		(SELECT TOP 1 CLCARD.SPECODE  
		FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSTRANS CSTRANS, {DATABASE}LG_{FIRMA}_CLCARD CLCARD 
		WHERE CSTRANS.CARDREF = CLCARD.LOGICALREF  AND CSTRANS.CSREF = CSCARD.LOGICALREF 
		ORDER BY CSTRANS.LOGICALREF DESC) AS [Özel Kod],
		DUEDATE AS [Vade],
		MONTH(DUEDATE)  AS [Vade Ay],
		YEAR (DUEDATE) AS [Vade Yıl],		
	amount*-1 AS [Tutar],
	CASE WHEN TRCURR = 0 THEN ''TL'' 
		 ELSE (Select CURCODE  FROM L_CURRENCYLIST WHERE CURTYPE = CSCARD.TRCURR AND FIRMNR = 001) END AS Döviz,
		 TRNET*-1 AS [Dövizli Tutar]
FROM {DATABASE}LG_{FIRMA}_{DONEM}_CSCARD CSCARD 
WHERE  DOC IN (3,4) AND CURRSTAT IN (9,10)


	  
UNION ALL
SELECT     ''Tahsilat'' AS Tür, ''Kredi Kartı'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı], CLCARD_2.SPECODE AS [Özel Kod], 
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl], case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL ) ELSE (PAYTRANS_2.TOTAL)*PAYTRANS_2.TRRATE END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 1) AND (PAYTRANS_2.MODULENR = ''5'') AND (PAYTRANS_2.TRCODE = ''70'')
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Kredi Kartı'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı], CLCARD_2.SPECODE AS [Özel Kod],
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl], case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL *-1) ELSE (PAYTRANS_2.TOTAL*-1)*PAYTRANS_2.TRRATE END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL*-1)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 0) AND (PAYTRANS_2.MODULENR = ''5'') AND (PAYTRANS_2.TRCODE = ''72'')
UNION ALL
SELECT     ''Tahsilat'' AS Tür, ''Açılış Fişi'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı],  CLCARD_2.SPECODE AS [Özel Kod],
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl],case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL ) ELSE (PAYTRANS_2.TOTAL)*PAYTRANS_2.TRRATE END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 0) AND (PAYTRANS_2.MODULENR = ''5'') AND 
                      (PAYTRANS_2.TOTAL - PAYTRANS_2.PAID > 0) AND (PAYTRANS_2.TRCODE = ''14'')
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Açılış Fişi'' AS Bölüm, CLCARD_2.CODE AS [Kodu], CLCARD_2.DEFINITION_ AS [Ünvanı],  CLCARD_2.SPECODE AS [Özel Kod],
                      PAYTRANS_2.DATE_ AS Vade, MONTH(PAYTRANS_2.DATE_) AS [Vade Ay], YEAR(PAYTRANS_2.DATE_) 
                      AS [Vade Yıl], case PAYTRANS_2.TRCURR WHEN 0 THEN (PAYTRANS_2.TOTAL *-1) ELSE (PAYTRANS_2.TOTAL)*PAYTRANS_2.TRRATE *-1 END AS Tutar,
					  case PAYTRANS_2.TRCURR WHEN 0 THEN ''TL'' else (SELECT CURCODE FROM L_CURRENCYLIST  WHERE FIRMNR={FIRMA} AND CURTYPE=PAYTRANS_2.TRCURR) end AS Döviz,
					   (PAYTRANS_2.TOTAL)  AS [Dövizli Tutar]
FROM         {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS AS PAYTRANS_2 INNER JOIN
                      {DATABASE}LG_{FIRMA}_CLCARD AS CLCARD_2 ON PAYTRANS_2.CARDREF = CLCARD_2.LOGICALREF
WHERE     (PAYTRANS_2.SIGN = 1) AND (PAYTRANS_2.MODULENR = ''5'') AND 
                      (PAYTRANS_2.TOTAL - PAYTRANS_2.PAID > 0) AND (PAYTRANS_2.TRCODE = ''14'')
UNION ALL
SELECT     ''Ödeme'' AS Tür, ''Banka Kredisi'' AS Bölüm, BANKACC.CODE AS Kodu, BANKACC.DEFINITION_ AS Ünvanı,  BANKACC.SPECODE AS [Özel Kod], 

                      BNCREPAYTR.DUEDATE AS Vade, MONTH(BNCREPAYTR.DUEDATE) AS [Vade Ay], YEAR(BNCREPAYTR.DUEDATE) 
                      AS [Vade Yıl], CASE WHEN BNCREPAYTR.TRANSTYPE=0 THEN (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL )* - 1  ELSE 
                      (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL ) END AS Tutar,''TL'' AS Döviz,CASE WHEN BNCREPAYTR.TRANSTYPE=0 THEN (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL )* - 1  ELSE 
                      (BNCREPAYTR.TOTAL + BNCREPAYTR.INTTOTAL + BNCREPAYTR.BSMVTOTAL ) END AS [Dövizli Tutar]

FROM         {DATABASE}LG_{FIRMA}_BNCREPAYTR AS BNCREPAYTR INNER JOIN
                      {DATABASE}LG_{FIRMA}_BNCREDITCARD AS BNCREDITCARD ON BNCREPAYTR.CREDITREF = BNCREDITCARD.LOGICALREF INNER JOIN
                      {DATABASE}LG_{FIRMA}_BANKACC  AS BANKACC ON BNCREDITCARD.BNCRACCREF = BANKACC.LOGICALREF
                      

', 8001, 4000)

      SET @QUERY = @QUERY1 + @QUERY2 + @QUERY3 + @QUERY4 + @QUERY5 + @QUERY6 + @QUERY7 + @QUERY8 + @QUERY9 + @QUERY10 + @QUERY11 + @QUERY12 + @QUERY13 + @QUERY14 + @QUERY15 + @QUERY16 + @QUERY17 + @QUERY18 + @QUERY19 + @QUERY20
      SET @QUERY = REPLACE(REPLACE(REPLACE(@QUERY, '{DATABASE}',@DB), '{FIRMA}',@FIRM), '{DONEM}', @DONEM)

     EXECUTE sp_executesql @QUERY;
END
GO
