    EXEC EMY_RAPOR_AYLIK_AMORTISMAN '','002','01' 
CREATE PROCEDURE EMY_RAPOR_AYLIK_AMORTISMAN @DB NVARCHAR(50), @FIRM NVARCHAR(3), @DONEM NVARCHAR(2)  
AS
BEGIN
     DECLARE @QUERY NVARCHAR(MAX)
     DECLARE @QUERY1 NVARCHAR(MAX)
     DECLARE @QUERY2 NVARCHAR(MAX)
     DECLARE @QUERY3 NVARCHAR(MAX)
     DECLARE @QUERY4 NVARCHAR(MAX)
     DECLARE @QUERY5 NVARCHAR(MAX)
     DECLARE @QUERY6 NVARCHAR(MAX)
     DECLARE @QUERY7 NVARCHAR(MAX)
     DECLARE @QUERY8 NVARCHAR(MAX)
     DECLARE @QUERY9 NVARCHAR(MAX)
     DECLARE @QUERY10 NVARCHAR(MAX)
     DECLARE @QUERY11 NVARCHAR(MAX)
     DECLARE @QUERY12 NVARCHAR(MAX)
     DECLARE @QUERY13 NVARCHAR(MAX)
     DECLARE @QUERY14 NVARCHAR(MAX)
     DECLARE @QUERY15 NVARCHAR(MAX)
     DECLARE @QUERY16 NVARCHAR(MAX)
     DECLARE @QUERY17 NVARCHAR(MAX)
     DECLARE @QUERY18 NVARCHAR(MAX)
     DECLARE @QUERY19 NVARCHAR(MAX)
     DECLARE @QUERY20 NVARCHAR(MAX)


     SET @QUERY1 = ''
     SET @QUERY2 = ''
     SET @QUERY3 = ''
     SET @QUERY4 = ''
     SET @QUERY5 = ''
     SET @QUERY6 = ''
     SET @QUERY7 = ''
     SET @QUERY8 = ''
     SET @QUERY9 = ''
     SET @QUERY10 = ''
     SET @QUERY11 = ''
     SET @QUERY12 = ''
     SET @QUERY13 = ''
     SET @QUERY14 = ''
     SET @QUERY15 = ''
     SET @QUERY16 = ''
     SET @QUERY17 = ''
     SET @QUERY18 = ''
     SET @QUERY19 = ''
     SET @QUERY20 = ''

     SET @QUERY1 = SUBSTRING('SELECT 
FAREGIST.DATEIN AS [Giriş Tarihi],
FAREGIST.DATEOFDEPR AS [Amortisman Başlangıcı],
FAREGIST.QUANTITY AS [Miktar],
ITEMS.CODE AS [Sabit Kıymet Kodu],
ITEMS.NAME AS [Sabit Kıymet Açıklaması],
FAREGIST.DEPRRATE AS [Amortisman Oranı],
FAREGIST.DEPRDUR AS [Amortisman Süresi],
FAYEAR.YEAR_ AS [Yıl],
FAYEAR.CALCMON AS [Ay],
FAYEAR.LOCFIGS2_PERDDEPR AS [Aylık Amortisman],
FAREGIST.INVALUE AS [Sabit Kıymet Maliyeti] 
FROM {DATABASE}LG_{FIRMA}_FAYEAR FAYEAR 
INNER JOIN {DATABASE}LG_{FIRMA}_FAREGIST FAREGIST ON FAYEAR.FREGREF=FAREGIST.LOGICALREF
INNER JOIN {DATABASE}LG_{FIRMA}_ITEMS ITEMS ON ITEMS.LOGICALREF=FAREGIST.CRDREF
WHERE ITEMS.ACTIVE = 0 AND FAREGIST.CANCELLED = 0 and ITEMS.CARDTYPE=4 AND FAYEAR.TABLETY=0', 1, 4000)

      SET @QUERY = @QUERY1 + @QUERY2 + @QUERY3 + @QUERY4 + @QUERY5 + @QUERY6 + @QUERY7 + @QUERY8 + @QUERY9 + @QUERY10 + @QUERY11 + @QUERY12 + @QUERY13 + @QUERY14 + @QUERY15 + @QUERY16 + @QUERY17 + @QUERY18 + @QUERY19 + @QUERY20
      SET @QUERY = REPLACE(REPLACE(REPLACE(@QUERY, '{DATABASE}',@DB), '{FIRMA}',@FIRM), '{DONEM}', @DONEM)

     EXECUTE sp_executesql @QUERY;
END
GO
