USE TIGER_FERCAM
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE DP_RAPOR_SON_ALIM_ENVANTER @DB NVARCHAR(50), @FIRM NVARCHAR(3), @DONEM NVARCHAR(2) ,
                                      @_BASTAR_VALUE DATETIME,
                                      @_BITTAR_VALUE DATETIME,
                                      @_KOD_VALUE NVARCHAR(50),
                                      @_OZELKOD_VALUE NVARCHAR(50),
                                      @_YETKIKODU_VALUE NVARCHAR(50),
                                      @_GRUPKODU_VALUE NVARCHAR(50)
 
AS
BEGIN
     DECLARE @QUERY NVARCHAR(MAX)
     DECLARE @QUERY1 NVARCHAR(MAX)
     DECLARE @QUERY2 NVARCHAR(MAX)
     DECLARE @QUERY3 NVARCHAR(MAX)
     DECLARE @QUERY4 NVARCHAR(MAX)
     DECLARE @QUERY5 NVARCHAR(MAX)
     DECLARE @QUERY6 NVARCHAR(MAX)
     DECLARE @QUERY7 NVARCHAR(MAX)
     DECLARE @QUERY8 NVARCHAR(MAX)
     DECLARE @QUERY9 NVARCHAR(MAX)
     DECLARE @QUERY10 NVARCHAR(MAX)
     DECLARE @QUERY11 NVARCHAR(MAX)
     DECLARE @QUERY12 NVARCHAR(MAX)
     DECLARE @QUERY13 NVARCHAR(MAX)
     DECLARE @QUERY14 NVARCHAR(MAX)
     DECLARE @QUERY15 NVARCHAR(MAX)
     DECLARE @QUERY16 NVARCHAR(MAX)
     DECLARE @QUERY17 NVARCHAR(MAX)
     DECLARE @QUERY18 NVARCHAR(MAX)
     DECLARE @QUERY19 NVARCHAR(MAX)
     DECLARE @QUERY20 NVARCHAR(MAX)

     DECLARE @PARAMETRELER NVARCHAR(MAX)

     SET @PARAMETRELER = N'@_BASTAR DATETIME,@_BITTAR DATETIME,@_KOD NVARCHAR(50),@_OZELKOD NVARCHAR(50),@_YETKIKODU NVARCHAR(50),@_GRUPKODU NVARCHAR(50)';

     SET @QUERY1 = ''
     SET @QUERY2 = ''
     SET @QUERY3 = ''
     SET @QUERY4 = ''
     SET @QUERY5 = ''
     SET @QUERY6 = ''
     SET @QUERY7 = ''
     SET @QUERY8 = ''
     SET @QUERY9 = ''
     SET @QUERY10 = ''
     SET @QUERY11 = ''
     SET @QUERY12 = ''
     SET @QUERY13 = ''
     SET @QUERY14 = ''
     SET @QUERY15 = ''
     SET @QUERY16 = ''
     SET @QUERY17 = ''
     SET @QUERY18 = ''
     SET @QUERY19 = ''
     SET @QUERY20 = ''

     SET @QUERY1 = SUBSTRING('select ITEMS.CODE as [Malzeme Kodu],ITEMS.NAME as [Malzeme Açıklaması],SUM(ONHAND) AS [Eldeki Miktar],
(SELECT (VATMATRAH/((AMOUNT*UINFO2)/UINFO1)) FROM {DATABASE}LG_{FIRMA}_{DONEM}_STLINE WHERE LOGICALREF IN(SELECT MAX(LOGICALREF) FROM {DATABASE}LG_{FIRMA}_{DONEM}_STLINE WHERE STOCKREF=ITEMS.LOGICALREF AND LINETYPE=0 AND TRCODE IN (1,14) AND CANCELLED=0 AND DATE_ <= @_BITTAR)) AS [Birim Fiyat] 
,(SUM(ONHAND) * (SELECT (VATMATRAH/((AMOUNT*UINFO2)/UINFO1)) FROM {DATABASE}LG_{FIRMA}_{DONEM}_STLINE WHERE LOGICALREF IN(SELECT MAX(LOGICALREF) FROM {DATABASE}LG_{FIRMA}_{DONEM}_STLINE WHERE STOCKREF=ITEMS.LOGICALREF AND LINETYPE=0 AND TRCODE IN (1,14) AND CANCELLED=0 and vatmatrah>0 AND DATE_ <= @_BITTAR))) as [Tutar],(SELECT NAME  FROM L_CAPIWHOUSE  WHERE FIRMNR={FIRMA} AND NR=STTOT.INVENNO) AS Ambar
 from {DATABASE}LG_{FIRMA}_ITEMS ITEMS,{DATABASE}LV_{FIRMA}_{DONEM}_STINVTOT STTOT 
WHERE ITEMS.LOGICALREF=STTOT.STOCKREF 
AND (STTOT.DATE_ BETWEEN @_BASTAR AND @_BITTAR )
and  (@_KOD='''' or ITEMS.CODE LIKE REPLACE(@_KOD,''*'',''%''))
and  (@_OZELKOD='''' or ITEMS.SPECODE LIKE REPLACE(@_OZELKOD,''*'',''%''))
and  (@_YETKIKODU='''' or ITEMS.CYPHCODE LIKE REPLACE(@_YETKIKODU,''*'',''%''))
and  (@_GRUPKODU='''' or ITEMS.STGRPCODE LIKE REPLACE(@_GRUPKODU,''*'',''%'')) AND STTOT.INVENNO<>-1
GROUP BY ITEMS.CODE,ITEMS.NAME,ITEMS.LOGICALREF,STTOT.INVENNO
', 1, 4000)

      SET @QUERY = @QUERY1 + @QUERY2 + @QUERY3 + @QUERY4 + @QUERY5 + @QUERY6 + @QUERY7 + @QUERY8 + @QUERY9 + @QUERY10 + @QUERY11 + @QUERY12 + @QUERY13 + @QUERY14 + @QUERY15 + @QUERY16 + @QUERY17 + @QUERY18 + @QUERY19 + @QUERY20
      SET @QUERY = REPLACE(REPLACE(REPLACE(@QUERY, '{DATABASE}',@DB), '{FIRMA}',@FIRM), '{DONEM}', @DONEM)

     EXECUTE sp_executesql @QUERY, @PARAMETRELER, @_BASTAR = @_BASTAR_VALUE, @_BITTAR = @_BITTAR_VALUE, @_KOD = @_KOD_VALUE, @_OZELKOD = @_OZELKOD_VALUE, @_YETKIKODU = @_YETKIKODU_VALUE, @_GRUPKODU = @_GRUPKODU_VALUE;
END
GO
