 
EXEC  EMY_RAPOR_BORCVADEANALIZI '','002','01','20190101','20211001','%%' 


CREATE PROCEDURE EMY_RAPOR_BORCVADEANALIZI @DB NVARCHAR(50), @FIRM NVARCHAR(3), @DONEM NVARCHAR(2) ,
                                      @_BASTAR_VALUE DATETIME,
                                      @_BITTAR_VALUE DATETIME,
                                      @_CARIKOD_VALUE NVARCHAR(50)
 
AS
BEGIN
     DECLARE @QUERY NVARCHAR(MAX)
     DECLARE @QUERY1 NVARCHAR(MAX)
     DECLARE @QUERY2 NVARCHAR(MAX)
     DECLARE @QUERY3 NVARCHAR(MAX)
     DECLARE @QUERY4 NVARCHAR(MAX)
     DECLARE @QUERY5 NVARCHAR(MAX)
     DECLARE @QUERY6 NVARCHAR(MAX)
     DECLARE @QUERY7 NVARCHAR(MAX)
     DECLARE @QUERY8 NVARCHAR(MAX)
     DECLARE @QUERY9 NVARCHAR(MAX)
     DECLARE @QUERY10 NVARCHAR(MAX)
     DECLARE @QUERY11 NVARCHAR(MAX)
     DECLARE @QUERY12 NVARCHAR(MAX)
     DECLARE @QUERY13 NVARCHAR(MAX)
     DECLARE @QUERY14 NVARCHAR(MAX)
     DECLARE @QUERY15 NVARCHAR(MAX)
     DECLARE @QUERY16 NVARCHAR(MAX)
     DECLARE @QUERY17 NVARCHAR(MAX)
     DECLARE @QUERY18 NVARCHAR(MAX)
     DECLARE @QUERY19 NVARCHAR(MAX)
     DECLARE @QUERY20 NVARCHAR(MAX)

     DECLARE @PARAMETRELER NVARCHAR(MAX)

     SET @PARAMETRELER = N'@_BASTAR DATETIME,@_BITTAR DATETIME,@_CARIKOD NVARCHAR(50)';

     SET @QUERY1 = ''
     SET @QUERY2 = ''
     SET @QUERY3 = ''
     SET @QUERY4 = ''
     SET @QUERY5 = ''
     SET @QUERY6 = ''
     SET @QUERY7 = ''
     SET @QUERY8 = ''
     SET @QUERY9 = ''
     SET @QUERY10 = ''
     SET @QUERY11 = ''
     SET @QUERY12 = ''
     SET @QUERY13 = ''
     SET @QUERY14 = ''
     SET @QUERY15 = ''
     SET @QUERY16 = ''
     SET @QUERY17 = ''
     SET @QUERY18 = ''
     SET @QUERY19 = ''
     SET @QUERY20 = ''

     SET @QUERY1 = SUBSTRING('SELECT 
CLCARD.CODE as "Cari Hesap Kodu",CLCARD.DEFINITION_  as "Cari Hesap Ünvanı"  ,CLCARD.SPECODE AS "Özel Kod",
ROUND(SUM(PAYTRANS.TOTAL*DATEDIFF(dd,PAYTRANS.PROCDATE ,PAYTRANS.DATE_)) / SUM(PAYTRANS.TOTAL),2) AS "Fatura Ortalama Vade",
ROUND(SUM(TAHSILAT.PAID*DATEDIFF(dd,PAYTRANS.DATE_,TAHSILAT.DATE_)) / SUM(TAHSILAT.PAID),2) AS "Tahsilat Gecikme",
ROUND(SUM(PAYTRANS.TOTAL*DATEDIFF(dd,PAYTRANS.PROCDATE ,PAYTRANS.DATE_)) / SUM(PAYTRANS.TOTAL)+

SUM(TAHSILAT.PAID*DATEDIFF(dd,PAYTRANS.DATE_,TAHSILAT.DATE_)) / SUM(TAHSILAT.PAID),2)  AS "Tahsilat Vade"

 FROM {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS PAYTRANS 
INNER JOIN {DATABASE}LG_{FIRMA}_CLCARD CLCARD ON PAYTRANS.CARDREF = CLCARD.LOGICALREF
INNER JOIN {DATABASE}LG_{FIRMA}_{DONEM}_PAYTRANS TAHSILAT ON PAYTRANS.CROSSREF = TAHSILAT.LOGICALREF AND TAHSILAT.SIGN = 1

WHERE  PAYTRANS.SIGN =0 AND PAYTRANS.CANCELLED =0
AND (@_CARIKOD='''' OR CLCARD.CODE LIKE REPLACE(@_CARIKOD,''*'',''%''))
AND  (PAYTRANS.PROCDATE BETWEEN @_BASTAR AND @_BITTAR)


GROUP BY CLCARD.CODE,CLCARD.DEFINITION_ ,CLCARD.SPECODE

', 1, 4000)

      SET @QUERY = @QUERY1 + @QUERY2 + @QUERY3 + @QUERY4 + @QUERY5 + @QUERY6 + @QUERY7 + @QUERY8 + @QUERY9 + @QUERY10 + @QUERY11 + @QUERY12 + @QUERY13 + @QUERY14 + @QUERY15 + @QUERY16 + @QUERY17 + @QUERY18 + @QUERY19 + @QUERY20
      SET @QUERY = REPLACE(REPLACE(REPLACE(@QUERY, '{DATABASE}',@DB), '{FIRMA}',@FIRM), '{DONEM}', @DONEM)

     EXECUTE sp_executesql @QUERY, @PARAMETRELER, @_BASTAR = @_BASTAR_VALUE, @_BITTAR = @_BITTAR_VALUE, @_CARIKOD = @_CARIKOD_VALUE;
END
GO
