
namespace E_Maliyet.Tiger.Forms
{
    using Serenity;
    using Serenity.ComponentModel;
    using Serenity.Data;
    using System;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.IO;

    [FormScript("Tiger.TigerFirmalar")]
    [BasedOnRow(typeof(Entities.TigerFirmalarRow), CheckNames = true)]
    public class TigerFirmalarForm
    {
        public Int16 Nr { get; set; }
        public String Name { get; set; }
        public String Title { get; set; }
        public String Street { get; set; }
        public String Road { get; set; }
        public String Doornr { get; set; }
        public String District { get; set; }
        public String City { get; set; }
        public String Country { get; set; }
        public String Zipcode { get; set; }
        public String Phone1 { get; set; }
        public String Phone2 { get; set; }
        public String Fax { get; set; }
        public String Taxoff { get; set; }
        public String Taxnr { get; set; }
        public String Securnr { get; set; }
        public String Direct { get; set; }
        public String Cpaname { get; set; }
        public String Cpastreet { get; set; }
        public String Cparoad { get; set; }
        public String Cpadoornr { get; set; }
        public String Cpadistrict { get; set; }
        public String Cpacity { get; set; }
        public String Cpaphone { get; set; }
        public String Cpataxoff { get; set; }
        public String Cpataxnr { get; set; }
        public String Cpachambnr { get; set; }
        public Int16 Begmon { get; set; }
        public Int16 Begday { get; set; }
        public Int32 Userext { get; set; }
        public Int16 Pernr { get; set; }
        public Int16 Countofleg { get; set; }
        public String Ctable { get; set; }
        public Int16 Workdayflgs1 { get; set; }
        public Int16 Workdayflgs2 { get; set; }
        public Int16 Workdayflgs3 { get; set; }
        public Int16 Workdayflgs4 { get; set; }
        public Int16 Workdayflgs5 { get; set; }
        public Int16 Workdayflgs6 { get; set; }
        public Int16 Workdayflgs7 { get; set; }
        public Int16 Localctyp { get; set; }
        public Int16 Firmrepcurr { get; set; }
        public Int16 Sepexchtable { get; set; }
        public Int16 Vatroundmtd { get; set; }
        public String Firmeuvatnumber { get; set; }
        public Int16 Majversnr { get; set; }
        public Int16 Minversnr { get; set; }
        public Int16 Relversnr { get; set; }
        public Int16 Siteid { get; set; }
        public Int32 Orgchart { get; set; }
        public Int16 Localcaldr { get; set; }
        public Int16 Firmlang { get; set; }
        public String Taxoffcode { get; set; }
        public String Cntrycode { get; set; }
        public Int16 Longperiods { get; set; }
        public String Logoid { get; set; }
        public String Emailaddr { get; set; }
        public String Webaddr { get; set; }
        public DateTime Moddate { get; set; }
        public Int32 Modtime { get; set; }
        public String Traderegisno { get; set; }
        public String Employername { get; set; }
        public String Employersurname { get; set; }
        public String Employeridtcno { get; set; }
        public String Employeremail { get; set; }
        public Int16 Firmytlstatus { get; set; }
        public Int16 Ytlsourcefirm { get; set; }
        public String Zusatzno { get; set; }
        public String Taxoffstatecd { get; set; }
        public String Taxoffstatenm { get; set; }
        public String Statecode { get; set; }
        public String Statename { get; set; }
        public String Cpaoccupation { get; set; }
        public String Cpaextension { get; set; }
        public String Cpaemail { get; set; }
        public String Cpasurname { get; set; }
        public String Cpaidtcno { get; set; }
        public String Accofficecode { get; set; }
        public Int16 Advancedproduct { get; set; }
        public String Bagkurnr { get; set; }
        public String Username { get; set; }
        public String Dbname { get; set; }
        public String Password { get; set; }
        public Int16 Actarea { get; set; }
        public Int16 Sector { get; set; }
        public String Srccriteria { get; set; }
        public Int32 Conscoderef { get; set; }
        public String Tcellappid { get; set; }
        public String Tcellapppw { get; set; }
        public Int16 Dncnstlen { get; set; }
        public Int16 Useserverdate { get; set; }
        public Int16 Usechangelog { get; set; }
        public String Mobusername { get; set; }
        public String Mobpassword { get; set; }
        public String Mobfirmalias { get; set; }
        public Int16 Accepteinv { get; set; }
        public String Einvoiceid { get; set; }
        public String Profileid { get; set; }
        public Int16 Usecommonparam { get; set; }
        public Int16 Passive { get; set; }
        public String Usercode { get; set; }
        public String Parole { get; set; }
        public String Passwordtaxdecl { get; set; }
        public String Firmemailaddr { get; set; }
        public Int16 Firmtype { get; set; }
        public String Nacecode { get; set; }
        public String Cpacountry { get; set; }
        public String Cpazipcode { get; set; }
        public String Cpafaxnr { get; set; }
        public String Cpacntrycode { get; set; }
        public Int16 Useebook { get; set; }
        public String Contractdesc { get; set; }
        public String Contracttype { get; set; }
        public DateTime Contractdate { get; set; }
        public String Contractnumber { get; set; }
        public String Hashvers { get; set; }
        public String Timestampuser { get; set; }
        public String Timestamppass { get; set; }
        public String Timestampserver { get; set; }
        public Int16 Useproxy { get; set; }
        public String Ptimestampuser { get; set; }
        public String Ptimestamppass { get; set; }
        public String Ptimestamphost { get; set; }
        public Int32 Ptimestampport { get; set; }
        public Int32 Timestampport { get; set; }
        public String Timestampapppth { get; set; }
        public String Jgserverurl { get; set; }
        public String Jgusername { get; set; }
        public String Jgpassword { get; set; }
        public Int32 Jgcompanynr { get; set; }
        public Int32 Jgperiodnr { get; set; }
        public String Jghrfirmcode { get; set; }
        public Double Deductlimit { get; set; }
        public String Postlabelcode { get; set; }
        public String Senderlabelcode { get; set; }
        public Int16 Einvconttype { get; set; }
        public Int16 Ebookconttype { get; set; }
        public String Mersisno { get; set; }
        public String Officaltitle { get; set; }
        public Int16 Useearchive { get; set; }
        public String Intsalesaddr { get; set; }
        public String Faxusername { get; set; }
        public String Faxuserkey { get; set; }
        public String Faxemailaddr { get; set; }
        public DateTime Ebookstartdate { get; set; }
        public Int16 Ebookcurrtype { get; set; }
        public Int16 Earcentsend { get; set; }
        public String Earcentuser { get; set; }
        public String Earcentpass { get; set; }
        public String Earcentdefaddr { get; set; }
        public Int16 Cpatitle { get; set; }
        public Int16 Isebookkeptbyfirm { get; set; }
        public Int16 Isymmcontractmade { get; set; }
        public String Ymmname { get; set; }
        public String Ymmsurname { get; set; }
        public String Ymmcontdesc { get; set; }
        public String Ymmconttype { get; set; }
        public Int32 Ymmcontdate { get; set; }
        public String Ymmcontnumber { get; set; }
        public Int32 Lastcontrolno { get; set; }
        public Int32 Lastjournalno { get; set; }
        public Int32 Lastgloblineno { get; set; }
        public Int16 Backupebooks { get; set; }
        public Int16 Einvcustom { get; set; }
        public String Ymmphone { get; set; }
        public String Ymmfaxnr { get; set; }
        public String Ymmemail { get; set; }
        public Int16 Einvoicetypsgk { get; set; }
        public String Taxpayercode { get; set; }
        public String Taxpayername { get; set; }
        public String Ymmchambnr { get; set; }
        public String Ymmtcno { get; set; }
        public String Ymmtaxnr { get; set; }
        public Int16 Useedespatch { get; set; }
        public String Postlabelcodedesp { get; set; }
        public String Senderlabelcodedesp { get; set; }
        public Int16 Shaalgorithm { get; set; }
        public Int16 Useeproducerrec { get; set; }
        public String Cpakdspassword { get; set; }
        public String Cpausername { get; set; }
        public Int16 Useetradesmaninv { get; set; }
        public Int32 Liquidatingdate { get; set; }
        public Int16 Liquidatedfirm { get; set; }
        public Int16 Getcpafromdiv { get; set; }
        public Int16 Liquidationtyp { get; set; }
        public Int16 Emutentsend { get; set; }
        public String Passwordtaxdecl2 { get; set; }
        public String Emutentuser { get; set; }
        public String Emutentdefaddr { get; set; }
        public String Emutentpass { get; set; }
        public Int16 Cpatckn { get; set; }
        public Int16 Usepaperinv { get; set; }
        public String Shpagncod { get; set; }
        public String Parole2 { get; set; }
        public String Usercode2 { get; set; }
    }
}