namespace E_Maliyet.Tiger {
    export interface TigerFirmalarForm {
        Nr: Serenity.IntegerEditor;
        Name: Serenity.StringEditor;
        Title: Serenity.StringEditor;
        Street: Serenity.StringEditor;
        Road: Serenity.StringEditor;
        Doornr: Serenity.StringEditor;
        District: Serenity.StringEditor;
        City: Serenity.StringEditor;
        Country: Serenity.StringEditor;
        Zipcode: Serenity.StringEditor;
        Phone1: Serenity.StringEditor;
        Phone2: Serenity.StringEditor;
        Fax: Serenity.StringEditor;
        Taxoff: Serenity.StringEditor;
        Taxnr: Serenity.StringEditor;
        Securnr: Serenity.StringEditor;
        Direct: Serenity.StringEditor;
        Cpaname: Serenity.StringEditor;
        Cpastreet: Serenity.StringEditor;
        Cparoad: Serenity.StringEditor;
        Cpadoornr: Serenity.StringEditor;
        Cpadistrict: Serenity.StringEditor;
        Cpacity: Serenity.StringEditor;
        Cpaphone: Serenity.StringEditor;
        Cpataxoff: Serenity.StringEditor;
        Cpataxnr: Serenity.StringEditor;
        Cpachambnr: Serenity.StringEditor;
        Begmon: Serenity.IntegerEditor;
        Begday: Serenity.IntegerEditor;
        Userext: Serenity.IntegerEditor;
        Pernr: Serenity.IntegerEditor;
        Countofleg: Serenity.IntegerEditor;
        Ctable: Serenity.StringEditor;
        Workdayflgs1: Serenity.IntegerEditor;
        Workdayflgs2: Serenity.IntegerEditor;
        Workdayflgs3: Serenity.IntegerEditor;
        Workdayflgs4: Serenity.IntegerEditor;
        Workdayflgs5: Serenity.IntegerEditor;
        Workdayflgs6: Serenity.IntegerEditor;
        Workdayflgs7: Serenity.IntegerEditor;
        Localctyp: Serenity.IntegerEditor;
        Firmrepcurr: Serenity.IntegerEditor;
        Sepexchtable: Serenity.IntegerEditor;
        Vatroundmtd: Serenity.IntegerEditor;
        Firmeuvatnumber: Serenity.StringEditor;
        Majversnr: Serenity.IntegerEditor;
        Minversnr: Serenity.IntegerEditor;
        Relversnr: Serenity.IntegerEditor;
        Siteid: Serenity.IntegerEditor;
        Orgchart: Serenity.IntegerEditor;
        Localcaldr: Serenity.IntegerEditor;
        Firmlang: Serenity.IntegerEditor;
        Taxoffcode: Serenity.StringEditor;
        Cntrycode: Serenity.StringEditor;
        Longperiods: Serenity.IntegerEditor;
        Logoid: Serenity.StringEditor;
        Emailaddr: Serenity.StringEditor;
        Webaddr: Serenity.StringEditor;
        Moddate: Serenity.DateEditor;
        Modtime: Serenity.IntegerEditor;
        Traderegisno: Serenity.StringEditor;
        Employername: Serenity.StringEditor;
        Employersurname: Serenity.StringEditor;
        Employeridtcno: Serenity.StringEditor;
        Employeremail: Serenity.StringEditor;
        Firmytlstatus: Serenity.IntegerEditor;
        Ytlsourcefirm: Serenity.IntegerEditor;
        Zusatzno: Serenity.StringEditor;
        Taxoffstatecd: Serenity.StringEditor;
        Taxoffstatenm: Serenity.StringEditor;
        Statecode: Serenity.StringEditor;
        Statename: Serenity.StringEditor;
        Cpaoccupation: Serenity.StringEditor;
        Cpaextension: Serenity.StringEditor;
        Cpaemail: Serenity.StringEditor;
        Cpasurname: Serenity.StringEditor;
        Cpaidtcno: Serenity.StringEditor;
        Accofficecode: Serenity.StringEditor;
        Advancedproduct: Serenity.IntegerEditor;
        Bagkurnr: Serenity.StringEditor;
        Username: Serenity.StringEditor;
        Dbname: Serenity.StringEditor;
        Password: Serenity.StringEditor;
        Actarea: Serenity.IntegerEditor;
        Sector: Serenity.IntegerEditor;
        Srccriteria: Serenity.StringEditor;
        Conscoderef: Serenity.IntegerEditor;
        Tcellappid: Serenity.StringEditor;
        Tcellapppw: Serenity.StringEditor;
        Dncnstlen: Serenity.IntegerEditor;
        Useserverdate: Serenity.IntegerEditor;
        Usechangelog: Serenity.IntegerEditor;
        Mobusername: Serenity.StringEditor;
        Mobpassword: Serenity.StringEditor;
        Mobfirmalias: Serenity.StringEditor;
        Accepteinv: Serenity.IntegerEditor;
        Einvoiceid: Serenity.StringEditor;
        Profileid: Serenity.StringEditor;
        Usecommonparam: Serenity.IntegerEditor;
        Passive: Serenity.IntegerEditor;
        Usercode: Serenity.StringEditor;
        Parole: Serenity.StringEditor;
        Passwordtaxdecl: Serenity.StringEditor;
        Firmemailaddr: Serenity.StringEditor;
        Firmtype: Serenity.IntegerEditor;
        Nacecode: Serenity.StringEditor;
        Cpacountry: Serenity.StringEditor;
        Cpazipcode: Serenity.StringEditor;
        Cpafaxnr: Serenity.StringEditor;
        Cpacntrycode: Serenity.StringEditor;
        Useebook: Serenity.IntegerEditor;
        Contractdesc: Serenity.StringEditor;
        Contracttype: Serenity.StringEditor;
        Contractdate: Serenity.DateEditor;
        Contractnumber: Serenity.StringEditor;
        Hashvers: Serenity.StringEditor;
        Timestampuser: Serenity.StringEditor;
        Timestamppass: Serenity.StringEditor;
        Timestampserver: Serenity.StringEditor;
        Useproxy: Serenity.IntegerEditor;
        Ptimestampuser: Serenity.StringEditor;
        Ptimestamppass: Serenity.StringEditor;
        Ptimestamphost: Serenity.StringEditor;
        Ptimestampport: Serenity.IntegerEditor;
        Timestampport: Serenity.IntegerEditor;
        Timestampapppth: Serenity.StringEditor;
        Jgserverurl: Serenity.StringEditor;
        Jgusername: Serenity.StringEditor;
        Jgpassword: Serenity.StringEditor;
        Jgcompanynr: Serenity.IntegerEditor;
        Jgperiodnr: Serenity.IntegerEditor;
        Jghrfirmcode: Serenity.StringEditor;
        Deductlimit: Serenity.DecimalEditor;
        Postlabelcode: Serenity.StringEditor;
        Senderlabelcode: Serenity.StringEditor;
        Einvconttype: Serenity.IntegerEditor;
        Ebookconttype: Serenity.IntegerEditor;
        Mersisno: Serenity.StringEditor;
        Officaltitle: Serenity.StringEditor;
        Useearchive: Serenity.IntegerEditor;
        Intsalesaddr: Serenity.StringEditor;
        Faxusername: Serenity.StringEditor;
        Faxuserkey: Serenity.StringEditor;
        Faxemailaddr: Serenity.StringEditor;
        Ebookstartdate: Serenity.DateEditor;
        Ebookcurrtype: Serenity.IntegerEditor;
        Earcentsend: Serenity.IntegerEditor;
        Earcentuser: Serenity.StringEditor;
        Earcentpass: Serenity.StringEditor;
        Earcentdefaddr: Serenity.StringEditor;
        Cpatitle: Serenity.IntegerEditor;
        Isebookkeptbyfirm: Serenity.IntegerEditor;
        Isymmcontractmade: Serenity.IntegerEditor;
        Ymmname: Serenity.StringEditor;
        Ymmsurname: Serenity.StringEditor;
        Ymmcontdesc: Serenity.StringEditor;
        Ymmconttype: Serenity.StringEditor;
        Ymmcontdate: Serenity.IntegerEditor;
        Ymmcontnumber: Serenity.StringEditor;
        Lastcontrolno: Serenity.IntegerEditor;
        Lastjournalno: Serenity.IntegerEditor;
        Lastgloblineno: Serenity.IntegerEditor;
        Backupebooks: Serenity.IntegerEditor;
        Einvcustom: Serenity.IntegerEditor;
        Ymmphone: Serenity.StringEditor;
        Ymmfaxnr: Serenity.StringEditor;
        Ymmemail: Serenity.StringEditor;
        Einvoicetypsgk: Serenity.IntegerEditor;
        Taxpayercode: Serenity.StringEditor;
        Taxpayername: Serenity.StringEditor;
        Ymmchambnr: Serenity.StringEditor;
        Ymmtcno: Serenity.StringEditor;
        Ymmtaxnr: Serenity.StringEditor;
        Useedespatch: Serenity.IntegerEditor;
        Postlabelcodedesp: Serenity.StringEditor;
        Senderlabelcodedesp: Serenity.StringEditor;
        Shaalgorithm: Serenity.IntegerEditor;
        Useeproducerrec: Serenity.IntegerEditor;
        Cpakdspassword: Serenity.StringEditor;
        Cpausername: Serenity.StringEditor;
        Useetradesmaninv: Serenity.IntegerEditor;
        Liquidatingdate: Serenity.IntegerEditor;
        Liquidatedfirm: Serenity.IntegerEditor;
        Getcpafromdiv: Serenity.IntegerEditor;
        Liquidationtyp: Serenity.IntegerEditor;
        Emutentsend: Serenity.IntegerEditor;
        Passwordtaxdecl2: Serenity.StringEditor;
        Emutentuser: Serenity.StringEditor;
        Emutentdefaddr: Serenity.StringEditor;
        Emutentpass: Serenity.StringEditor;
        Cpatckn: Serenity.IntegerEditor;
        Usepaperinv: Serenity.IntegerEditor;
        Shpagncod: Serenity.StringEditor;
        Parole2: Serenity.StringEditor;
        Usercode2: Serenity.StringEditor;
    }

    export class TigerFirmalarForm extends Serenity.PrefixedContext {
        static formKey = 'Tiger.TigerFirmalar';
        private static init: boolean;

        constructor(prefix: string) {
            super(prefix);

            if (!TigerFirmalarForm.init)  {
                TigerFirmalarForm.init = true;

                var s = Serenity;
                var w0 = s.IntegerEditor;
                var w1 = s.StringEditor;
                var w2 = s.DateEditor;
                var w3 = s.DecimalEditor;

                Q.initFormType(TigerFirmalarForm, [
                    'Nr', w0,
                    'Name', w1,
                    'Title', w1,
                    'Street', w1,
                    'Road', w1,
                    'Doornr', w1,
                    'District', w1,
                    'City', w1,
                    'Country', w1,
                    'Zipcode', w1,
                    'Phone1', w1,
                    'Phone2', w1,
                    'Fax', w1,
                    'Taxoff', w1,
                    'Taxnr', w1,
                    'Securnr', w1,
                    'Direct', w1,
                    'Cpaname', w1,
                    'Cpastreet', w1,
                    'Cparoad', w1,
                    'Cpadoornr', w1,
                    'Cpadistrict', w1,
                    'Cpacity', w1,
                    'Cpaphone', w1,
                    'Cpataxoff', w1,
                    'Cpataxnr', w1,
                    'Cpachambnr', w1,
                    'Begmon', w0,
                    'Begday', w0,
                    'Userext', w0,
                    'Pernr', w0,
                    'Countofleg', w0,
                    'Ctable', w1,
                    'Workdayflgs1', w0,
                    'Workdayflgs2', w0,
                    'Workdayflgs3', w0,
                    'Workdayflgs4', w0,
                    'Workdayflgs5', w0,
                    'Workdayflgs6', w0,
                    'Workdayflgs7', w0,
                    'Localctyp', w0,
                    'Firmrepcurr', w0,
                    'Sepexchtable', w0,
                    'Vatroundmtd', w0,
                    'Firmeuvatnumber', w1,
                    'Majversnr', w0,
                    'Minversnr', w0,
                    'Relversnr', w0,
                    'Siteid', w0,
                    'Orgchart', w0,
                    'Localcaldr', w0,
                    'Firmlang', w0,
                    'Taxoffcode', w1,
                    'Cntrycode', w1,
                    'Longperiods', w0,
                    'Logoid', w1,
                    'Emailaddr', w1,
                    'Webaddr', w1,
                    'Moddate', w2,
                    'Modtime', w0,
                    'Traderegisno', w1,
                    'Employername', w1,
                    'Employersurname', w1,
                    'Employeridtcno', w1,
                    'Employeremail', w1,
                    'Firmytlstatus', w0,
                    'Ytlsourcefirm', w0,
                    'Zusatzno', w1,
                    'Taxoffstatecd', w1,
                    'Taxoffstatenm', w1,
                    'Statecode', w1,
                    'Statename', w1,
                    'Cpaoccupation', w1,
                    'Cpaextension', w1,
                    'Cpaemail', w1,
                    'Cpasurname', w1,
                    'Cpaidtcno', w1,
                    'Accofficecode', w1,
                    'Advancedproduct', w0,
                    'Bagkurnr', w1,
                    'Username', w1,
                    'Dbname', w1,
                    'Password', w1,
                    'Actarea', w0,
                    'Sector', w0,
                    'Srccriteria', w1,
                    'Conscoderef', w0,
                    'Tcellappid', w1,
                    'Tcellapppw', w1,
                    'Dncnstlen', w0,
                    'Useserverdate', w0,
                    'Usechangelog', w0,
                    'Mobusername', w1,
                    'Mobpassword', w1,
                    'Mobfirmalias', w1,
                    'Accepteinv', w0,
                    'Einvoiceid', w1,
                    'Profileid', w1,
                    'Usecommonparam', w0,
                    'Passive', w0,
                    'Usercode', w1,
                    'Parole', w1,
                    'Passwordtaxdecl', w1,
                    'Firmemailaddr', w1,
                    'Firmtype', w0,
                    'Nacecode', w1,
                    'Cpacountry', w1,
                    'Cpazipcode', w1,
                    'Cpafaxnr', w1,
                    'Cpacntrycode', w1,
                    'Useebook', w0,
                    'Contractdesc', w1,
                    'Contracttype', w1,
                    'Contractdate', w2,
                    'Contractnumber', w1,
                    'Hashvers', w1,
                    'Timestampuser', w1,
                    'Timestamppass', w1,
                    'Timestampserver', w1,
                    'Useproxy', w0,
                    'Ptimestampuser', w1,
                    'Ptimestamppass', w1,
                    'Ptimestamphost', w1,
                    'Ptimestampport', w0,
                    'Timestampport', w0,
                    'Timestampapppth', w1,
                    'Jgserverurl', w1,
                    'Jgusername', w1,
                    'Jgpassword', w1,
                    'Jgcompanynr', w0,
                    'Jgperiodnr', w0,
                    'Jghrfirmcode', w1,
                    'Deductlimit', w3,
                    'Postlabelcode', w1,
                    'Senderlabelcode', w1,
                    'Einvconttype', w0,
                    'Ebookconttype', w0,
                    'Mersisno', w1,
                    'Officaltitle', w1,
                    'Useearchive', w0,
                    'Intsalesaddr', w1,
                    'Faxusername', w1,
                    'Faxuserkey', w1,
                    'Faxemailaddr', w1,
                    'Ebookstartdate', w2,
                    'Ebookcurrtype', w0,
                    'Earcentsend', w0,
                    'Earcentuser', w1,
                    'Earcentpass', w1,
                    'Earcentdefaddr', w1,
                    'Cpatitle', w0,
                    'Isebookkeptbyfirm', w0,
                    'Isymmcontractmade', w0,
                    'Ymmname', w1,
                    'Ymmsurname', w1,
                    'Ymmcontdesc', w1,
                    'Ymmconttype', w1,
                    'Ymmcontdate', w0,
                    'Ymmcontnumber', w1,
                    'Lastcontrolno', w0,
                    'Lastjournalno', w0,
                    'Lastgloblineno', w0,
                    'Backupebooks', w0,
                    'Einvcustom', w0,
                    'Ymmphone', w1,
                    'Ymmfaxnr', w1,
                    'Ymmemail', w1,
                    'Einvoicetypsgk', w0,
                    'Taxpayercode', w1,
                    'Taxpayername', w1,
                    'Ymmchambnr', w1,
                    'Ymmtcno', w1,
                    'Ymmtaxnr', w1,
                    'Useedespatch', w0,
                    'Postlabelcodedesp', w1,
                    'Senderlabelcodedesp', w1,
                    'Shaalgorithm', w0,
                    'Useeproducerrec', w0,
                    'Cpakdspassword', w1,
                    'Cpausername', w1,
                    'Useetradesmaninv', w0,
                    'Liquidatingdate', w0,
                    'Liquidatedfirm', w0,
                    'Getcpafromdiv', w0,
                    'Liquidationtyp', w0,
                    'Emutentsend', w0,
                    'Passwordtaxdecl2', w1,
                    'Emutentuser', w1,
                    'Emutentdefaddr', w1,
                    'Emutentpass', w1,
                    'Cpatckn', w0,
                    'Usepaperinv', w0,
                    'Shpagncod', w1,
                    'Parole2', w1,
                    'Usercode2', w1
                ]);
            }
        }
    }
}
